package com.gcaguilar.biciradar.core

import kotlinx.serialization.Serializable

@Serializable
enum class City(
    val id: String,
    val displayName: String,
    val gbfsDiscoveryUrl: String,
    val defaultLatitude: Double,
    val defaultLongitude: Double,
    val supportsUsagePatterns: Boolean,
    val supportsEbikes: Boolean,
) {
    ZARAGOZA(
        id = "zaragoza",
        displayName = "Zaragoza",
        gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/bizi/gbfs.json",
        defaultLatitude = 41.6488,
        defaultLongitude = -0.8751,
        supportsUsagePatterns = true,
        supportsEbikes = true,
    ),
    MADRID(
        id = "madrid",
        displayName = "Madrid",
        gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/bicimad/gbfs.json",
        defaultLatitude = 40.4168,
        defaultLongitude = -3.7038,
        supportsUsagePatterns = false,
        supportsEbikes = true,
    ),
    BARCELONA(
        id = "barcelona",
        displayName = "Barcelona",
        gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/bicing/gbfs.json",
        defaultLatitude = 41.3851,
        defaultLongitude = 2.1734,
        supportsUsagePatterns = false,
        supportsEbikes = true,
    ),
    VALENCIA(
        id = "valencia",
        displayName = "Valencia",
        gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/mibisivalencia/gbfs.json",
        defaultLatitude = 39.4699,
        defaultLongitude = -0.3763,
        supportsUsagePatterns = false,
        supportsEbikes = true,
    ),
    SEVILLA(
        id = "sevilla",
        displayName = "Sevilla",
        gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/sevici/gbfs.json",
        defaultLatitude = 37.3891,
        defaultLongitude = -5.9845,
        supportsUsagePatterns = false,
        supportsEbikes = true,
    ),
    BILBAO(
        id = "bilbao",
        displayName = "Bilbao",
        gbfsDiscoveryUrl = "https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_bw/gbfs.json",
        defaultLatitude = 43.2630,
        defaultLongitude = -2.9350,
        supportsUsagePatterns = false,
        supportsEbikes = true,
    ),
    BIZKAIA(
        id = "bizkaia",
        displayName = "Bizkaia",
        gbfsDiscoveryUrl = "https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_bn/gbfs.json",
        defaultLatitude = 43.2565,
        defaultLongitude = -2.9236,
        supportsUsagePatterns = false,
        supportsEbikes = true,
    ),
    LEON(
        id = "leon",
        displayName = "León",
        gbfsDiscoveryUrl = "https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_le/gbfs.json",
        defaultLatitude = 42.5987,
        defaultLongitude = -5.5701,
        supportsUsagePatterns = false,
        supportsEbikes = true,
    ),
    VALLADOLID(
        id = "valladolid",
        displayName = "Valladolid",
        gbfsDiscoveryUrl = "https://vll.publicbikesystem.net/ube/gbfs/v1/gbfs.json",
        defaultLatitude = 41.6234,
        defaultLongitude = -4.7515,
        supportsUsagePatterns = false,
        supportsEbikes = true,
    ),
    MALAGA(
        id = "malaga",
        displayName = "Málaga",
        gbfsDiscoveryUrl = "https://api.citybik.es/v2/networks/malagabici/gbfs.json",
        defaultLatitude = 36.7213,
        defaultLongitude = -4.4214,
        supportsUsagePatterns = false,
        supportsEbikes = true,
    ),
    PALMA(
        id = "palma",
        displayName = "Palma de Mallorca",
        gbfsDiscoveryUrl = "https://api.citybik.es/v2/networks/bicipalma/gbfs.json",
        defaultLatitude = 39.5696,
        defaultLongitude = 2.6502,
        supportsUsagePatterns = false,
        supportsEbikes = true,
    ),
    LAS_PALMAS(
        id = "las_palmas",
        displayName = "Las Palmas",
        gbfsDiscoveryUrl = "https://api.citybik.es/v2/networks/sitycleta/gbfs.json",
        defaultLatitude = 28.1248,
        defaultLongitude = -15.4300,
        supportsUsagePatterns = false,
        supportsEbikes = true,
    ),
    A_CORUNA(
        id = "a_coruna",
        displayName = "A Coruña",
        gbfsDiscoveryUrl = "https://acoruna.publicbikesystem.net/customer/gbfs/v2/gbfs.json",
        defaultLatitude = 43.3623,
        defaultLongitude = -8.4115,
        supportsUsagePatterns = false,
        supportsEbikes = true,
    ),
    MISLATA(
        id = "mislata",
        displayName = "Mislata",
        gbfsDiscoveryUrl = "https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_ad/gbfs.json",
        defaultLatitude = 39.4743,
        defaultLongitude = -0.4184,
        supportsUsagePatterns = false,
        supportsEbikes = true,
    ),
    RIVAS_VACIAMADRID(
        id = "rivas",
        displayName = "Rivas-Vaciamadrid",
        gbfsDiscoveryUrl = "https://rivas.publicbikesystem.net/customer/gbfs/v2/gbfs.json",
        defaultLatitude = 40.3270,
        defaultLongitude = -3.5145,
        supportsUsagePatterns = false,
        supportsEbikes = true,
    ),
    DONOSTIA(
        id = "donostia",
        displayName = "Donostia",
        gbfsDiscoveryUrl = "https://sansebastian.publicbikesystem.net/customer/gbfs/v2/gbfs.json",
        defaultLatitude = 43.3201,
        defaultLongitude = -1.9838,
        supportsUsagePatterns = false,
        supportsEbikes = true,
    ),
    REUS(
        id = "reus",
        displayName = "Reus",
        gbfsDiscoveryUrl = "https://gbfs.ganxeta.cat/v2/gbfs.json",
        defaultLatitude = 41.1579,
        defaultLongitude = 1.1083,
        supportsUsagePatterns = false,
        supportsEbikes = true,
    ),
    SANTANDER(
        id = "santander",
        displayName = "Santander",
        gbfsDiscoveryUrl = "https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_ek/gbfs.json",
        defaultLatitude = 43.4623,
        defaultLongitude = -3.8099,
        supportsUsagePatterns = false,
        supportsEbikes = true,
    );

    companion object {
        fun fromId(id: String): City? = entries.find { it.id == id }

        fun defaultCity(): City = ZARAGOZA
    }
}
