package com.gcaguilar.biciradar.core

import kotlinx.serialization.Serializable

@Serializable
enum class City(
  val id: String,
  val displayName: String,
  val gbfsDiscoveryUrl: String,
  val defaultLatitude: Double,
  val defaultLongitude: Double,
  val supportsUsagePatterns: Boolean,
  val supportsEbikes: Boolean,
) {
  ZARAGOZA(
    id = "zaragoza",
    displayName = "Zaragoza",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/bizi/gbfs.json",
    defaultLatitude = 41.6488,
    defaultLongitude = -0.8751,
    supportsUsagePatterns = true,
    supportsEbikes = true,
  ),
  MADRID(
    id = "madrid",
    displayName = "Madrid",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/bicimad/gbfs.json",
    defaultLatitude = 40.4168,
    defaultLongitude = -3.7038,
    supportsUsagePatterns = false,
    supportsEbikes = true,
  ),
  BARCELONA(
    id = "barcelona",
    displayName = "Barcelona",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/bicing/gbfs.json",
    defaultLatitude = 41.3851,
    defaultLongitude = 2.1734,
    supportsUsagePatterns = false,
    supportsEbikes = true,
  ),
  VALENCIA(
    id = "valencia",
    displayName = "Valencia",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/valenbisi/gbfs.json",
    defaultLatitude = 39.4717,
    defaultLongitude = -0.3713,
    supportsUsagePatterns = false,
    supportsEbikes = true,
  ),
  SEVILLA(
    id = "sevilla",
    displayName = "Sevilla",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/sevici/gbfs.json",
    defaultLatitude = 37.3891,
    defaultLongitude = -5.9845,
    supportsUsagePatterns = false,
    supportsEbikes = true,
  ),
  MURCIA(
    id = "murcia",
    displayName = "Murcia",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/dott-murcia/gbfs.json",
    defaultLatitude = 37.9926,
    defaultLongitude = -1.1345,
    supportsUsagePatterns = false,
    supportsEbikes = true,
  ),
  BILBAO(
    id = "bilbao",
    displayName = "Bilbao",
    gbfsDiscoveryUrl = "https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_bw/gbfs.json",
    defaultLatitude = 43.2630,
    defaultLongitude = -2.9350,
    supportsUsagePatterns = false,
    supportsEbikes = true,
  ),
  BIZKAIA(
    id = "bizkaia",
    displayName = "Bizkaia",
    gbfsDiscoveryUrl = "https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_bn/gbfs.json",
    defaultLatitude = 43.2565,
    defaultLongitude = -2.9236,
    supportsUsagePatterns = false,
    supportsEbikes = true,
  ),
  LEON(
    id = "leon",
    displayName = "León",
    gbfsDiscoveryUrl = "https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_le/gbfs.json",
    defaultLatitude = 42.5987,
    defaultLongitude = -5.5701,
    supportsUsagePatterns = false,
    supportsEbikes = true,
  ),
  VALLADOLID(
    id = "valladolid",
    displayName = "Valladolid",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/biki/gbfs.json",
    defaultLatitude = 41.6234,
    defaultLongitude = -4.7515,
    supportsUsagePatterns = false,
    supportsEbikes = true,
  ),
  PALMA(
    id = "palma",
    displayName = "Palma de Mallorca",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/bicipalma/gbfs.json",
    defaultLatitude = 39.5696,
    defaultLongitude = 2.6502,
    supportsUsagePatterns = false,
    supportsEbikes = true,
  ),
  LAS_PALMAS(
    id = "las_palmas",
    displayName = "Las Palmas",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/sitycleta-las-palmas-las-palmas-de-gran-canaria/gbfs.json",
    defaultLatitude = 28.1248,
    defaultLongitude = -15.4300,
    supportsUsagePatterns = false,
    supportsEbikes = true,
  ),
  A_CORUNA(
    id = "a_coruna",
    displayName = "A Coruña",
    gbfsDiscoveryUrl = "https://acoruna.publicbikesystem.net/customer/gbfs/v2/gbfs.json",
    defaultLatitude = 43.3623,
    defaultLongitude = -8.4115,
    supportsUsagePatterns = false,
    supportsEbikes = true,
  ),
  MISLATA(
    id = "mislata",
    displayName = "Mislata",
    gbfsDiscoveryUrl = "https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_ad/gbfs.json",
    defaultLatitude = 39.4743,
    defaultLongitude = -0.4184,
    supportsUsagePatterns = false,
    supportsEbikes = true,
  ),
  RIVAS_VACIAMADRID(
    id = "rivas",
    displayName = "Rivas-Vaciamadrid",
    gbfsDiscoveryUrl = "https://rivas.publicbikesystem.net/customer/gbfs/v2/gbfs.json",
    defaultLatitude = 40.3270,
    defaultLongitude = -3.5145,
    supportsUsagePatterns = false,
    supportsEbikes = true,
  ),
  DONOSTIA(
    id = "donostia",
    displayName = "Donostia",
    gbfsDiscoveryUrl = "https://sansebastian.publicbikesystem.net/customer/gbfs/v2/gbfs.json",
    defaultLatitude = 43.3201,
    defaultLongitude = -1.9838,
    supportsUsagePatterns = false,
    supportsEbikes = true,
  ),
  REUS(
    id = "reus",
    displayName = "Reus",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/ganxeta-reus/gbfs.json",
    defaultLatitude = 41.1579,
    defaultLongitude = 1.1083,
    supportsUsagePatterns = false,
    supportsEbikes = true,
  ),
  SANTANDER(
    id = "santander",
    displayName = "Santander",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/tuebici/gbfs.json",
    defaultLatitude = 43.4625,
    defaultLongitude = -3.8189,
    supportsUsagePatterns = false,
    supportsEbikes = true,
  ),
  ALBACETE(
    id = "albacete",
    displayName = "Albacete",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/albabici/gbfs.json",
    defaultLatitude = 38.9927,
    defaultLongitude = -1.8591,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  ALCAZAR_DE_SAN_JUAN(
    id = "alcazar_de_san_juan",
    displayName = "Alcázar de San Juan",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/bicialcazar/gbfs.json",
    defaultLatitude = 39.3893,
    defaultLongitude = -3.2067,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  ALLER(
    id = "aller",
    displayName = "Aller",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/bealler/gbfs.json",
    defaultLatitude = 43.1458,
    defaultLongitude = -5.6279,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  ARTEIXO(
    id = "arteixo",
    displayName = "Arteixo",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/biciarteixo/gbfs.json",
    defaultLatitude = 43.3122,
    defaultLongitude = -8.5062,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  AVILES(
    id = "aviles",
    displayName = "Avilés",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/aviles-en-bici/gbfs.json",
    defaultLatitude = 43.5512,
    defaultLongitude = -5.9188,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  BADAJOZ(
    id = "badajoz",
    displayName = "Badajoz",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/biba/gbfs.json",
    defaultLatitude = 38.8778,
    defaultLongitude = -6.9814,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  BOADILLA_DEL_MONTE(
    id = "boadilla_del_monte",
    displayName = "Boadilla del Monte",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/bibo/gbfs.json",
    defaultLatitude = 40.4159,
    defaultLongitude = -3.8940,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  BURGOS(
    id = "burgos",
    displayName = "Burgos",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/bicibur/gbfs.json",
    defaultLatitude = 42.3478,
    defaultLongitude = -3.6907,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  CALDAS_DE_REIS(
    id = "caldas_de_reis",
    displayName = "Caldas de Reis",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/verdeciclos/gbfs.json",
    defaultLatitude = 42.6036,
    defaultLongitude = -8.6452,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  CAMPOO_DE_ENMEDIO(
    id = "campoo_de_enmedio",
    displayName = "Campoo de Enmedio",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/bikenmedio/gbfs.json",
    defaultLatitude = 42.9922,
    defaultLongitude = -4.1504,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  CASTELLON(
    id = "castellon",
    displayName = "Castellón",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/bicicas/gbfs.json",
    defaultLatitude = 39.9859,
    defaultLongitude = -0.0392,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  CASTRO_URDIALES(
    id = "castro_urdiales",
    displayName = "Castro-Urdiales",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/bicicastro/gbfs.json",
    defaultLatitude = 43.3720,
    defaultLongitude = -3.2284,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  CENICIENTOS(
    id = "cenicientos",
    displayName = "Cenicientos",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/cenibici/gbfs.json",
    defaultLatitude = 40.2637,
    defaultLongitude = -4.4683,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  ELX(
    id = "elx",
    displayName = "Elx",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/bicielx/gbfs.json",
    defaultLatitude = 38.2686,
    defaultLongitude = -0.6938,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  FERROL(
    id = "ferrol",
    displayName = "Ferrol",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/bici-ferrol-terra/gbfs.json",
    defaultLatitude = 43.4964,
    defaultLongitude = -8.2096,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  FUERTEVENTURA(
    id = "fuerteventura",
    displayName = "Fuerteventura",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/lovesharing-canary-islands-fuerteventura/gbfs.json",
    defaultLatitude = 28.2235,
    defaultLongitude = -14.1026,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  GETAFE(
    id = "getafe",
    displayName = "Getafe",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/gbici/gbfs.json",
    defaultLatitude = 40.3125,
    defaultLongitude = -3.7281,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  GIJON(
    id = "gijon",
    displayName = "Gijón",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/gijon/gbfs.json",
    defaultLatitude = 43.5327,
    defaultLongitude = -5.6638,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  GIRONA(
    id = "girona",
    displayName = "Girona",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/girocleta/gbfs.json",
    defaultLatitude = 41.9806,
    defaultLongitude = 2.8156,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  GRAN_CANARIA(
    id = "gran_canaria",
    displayName = "Gran Canaria",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/lovesharing-canary-islands-gran-canaria/gbfs.json",
    defaultLatitude = 27.7707,
    defaultLongitude = -15.6401,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  IBIZA(
    id = "ibiza",
    displayName = "Ibiza",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/dott-ibiza/gbfs.json",
    defaultLatitude = 38.9085,
    defaultLongitude = 1.4280,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  ILLA_DE_AROUSA(
    id = "illa_de_arousa",
    displayName = "A Illa de Arousa",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/biciarousa/gbfs.json",
    defaultLatitude = 42.5471,
    defaultLongitude = -8.8664,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  LANZAROTE(
    id = "lanzarote",
    displayName = "Lanzarote",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/lovesharing-canary-islands-lanzarote/gbfs.json",
    defaultLatitude = 28.9266,
    defaultLongitude = -13.6739,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  LOGRONO(
    id = "logrono",
    displayName = "Logroño",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/bicilog/gbfs.json",
    defaultLatitude = 42.4621,
    defaultLongitude = -2.4468,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  ONTINYENT(
    id = "ontinyent",
    displayName = "Ontinyent",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/ontibici/gbfs.json",
    defaultLatitude = 38.8206,
    defaultLongitude = -0.6069,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  PAMPLONA(
    id = "pamplona",
    displayName = "Pamplona",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/nbici/gbfs.json",
    defaultLatitude = 42.8117,
    defaultLongitude = -1.6487,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  SANT_VICENT_DEL_RASPEIG(
    id = "sant_vicent_del_raspeig",
    displayName = "Sant Vicent del Raspeig",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/bicisanvi/gbfs.json",
    defaultLatitude = 38.3928,
    defaultLongitude = -0.5207,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  TARRAGONA(
    id = "tarragona",
    displayName = "Tarragona",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/dott-tarragona/gbfs.json",
    defaultLatitude = 41.1200,
    defaultLongitude = 1.2503,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  TORRENT(
    id = "torrent",
    displayName = "Torrent",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/torrentbici/gbfs.json",
    defaultLatitude = 39.4317,
    defaultLongitude = -0.4722,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  URDAIBAI(
    id = "urdaibai",
    displayName = "Urdaibai",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/nextbike-urdaibai/gbfs.json",
    defaultLatitude = 43.3555,
    defaultLongitude = -2.7444,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  VILAGARCIA_DE_AROUSA(
    id = "vilagarcia_de_arousa",
    displayName = "Vilagarcía de Arousa",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/vaibike/gbfs.json",
    defaultLatitude = 42.5946,
    defaultLongitude = -8.7728,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  VILLARCAYO(
    id = "villarcayo",
    displayName = "Villarcayo",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/vive-villarcayo/gbfs.json",
    defaultLatitude = 42.9467,
    defaultLongitude = -3.5701,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  VITORIA_GASTEIZ(
    id = "vitoria_gasteiz",
    displayName = "Vitoria-Gasteiz",
    gbfsDiscoveryUrl = "https://api.citybik.es/gbfs/2/mugibike/gbfs.json",
    defaultLatitude = 42.8512,
    defaultLongitude = -2.6805,
    supportsUsagePatterns = false,
    supportsEbikes = false,
  ),
  ;

  companion object {
    fun fromId(id: String): City? = entries.find { it.id == id }

    fun defaultCity(): City = ZARAGOZA
  }
}
