package com.gcaguilar.biciradar.core

enum class AppLanguage {
  ES,
  EN,
  CA,
  EU,
  GL,
}

expect fun currentAppLanguage(): AppLanguage

private val localizedTextByKey: Map<String, Map<AppLanguage, String>> = mapOf(
  "Estado de estación" to mapOf(AppLanguage.EN to "Station status", AppLanguage.CA to "Estat de l'estació", AppLanguage.EU to "Geltokiaren egoera", AppLanguage.GL to "Estado da estación"),
  "Ruta a estación" to mapOf(AppLanguage.EN to "Route to station", AppLanguage.CA to "Ruta a l'estació", AppLanguage.EU to "Geltokirako ibilbidea", AppLanguage.GL to "Ruta á estación"),
  "Huecos en estación" to mapOf(AppLanguage.EN to "Slots at station", AppLanguage.CA to "Ancoratges a l'estació", AppLanguage.EU to "Lekuak geltokian", AppLanguage.GL to "Ocos na estación"),
  "Bicis en estación" to mapOf(AppLanguage.EN to "Bikes at station", AppLanguage.CA to "Bicis a l'estació", AppLanguage.EU to "Bizikletak geltokian", AppLanguage.GL to "Bicis na estación"),
  "Cercana con huecos" to mapOf(AppLanguage.EN to "Nearby with slots", AppLanguage.CA to "Propera amb ancoratges", AppLanguage.EU to "Lekuak dituen gertukoa", AppLanguage.GL to "Próxima con ocos"),
  "Cercana con bicis" to mapOf(AppLanguage.EN to "Nearby with bikes", AppLanguage.CA to "Propera amb bicis", AppLanguage.EU to "Bizikletadun gertukoa", AppLanguage.GL to "Próxima con bicis"),
  "Mis favoritas" to mapOf(AppLanguage.EN to "My favorites", AppLanguage.CA to "Les meves favorites", AppLanguage.EU to "Nire gogokoak", AppLanguage.GL to "As miñas favoritas"),
  "%s m · %s bicis · %s huecos" to mapOf(AppLanguage.EN to "%s m · %s bikes · %s slots", AppLanguage.CA to "%s m · %s bicis · %s ancoratges", AppLanguage.EU to "%s m · %s bizikleta · %s leku", AppLanguage.GL to "%s m · %s bicis · %s ocos"),
  "No hay dentro de %s m. La más cercana está a %s m." to mapOf(AppLanguage.EN to "None within %s m. The nearest is %s m away.", AppLanguage.CA to "No n'hi ha dins de %s m. La més propera és a %s m.", AppLanguage.EU to "Ez dago %s m barruan. Hurbilena %s m-ra dago.", AppLanguage.GL to "Non hai dentro de %s m. A máis próxima está a %s m."),
  "Actualiza estaciones para poder abrir la ruta." to mapOf(AppLanguage.EN to "Refresh stations to open the route.", AppLanguage.CA to "Actualitza estacions per poder obrir la ruta.", AppLanguage.EU to "Eguneratu geltokiak ibilbidea ireki ahal izateko.", AppLanguage.GL to "Actualiza as estacións para poder abrir a ruta."),
  "Limpiar búsqueda" to mapOf(AppLanguage.EN to "Clear search", AppLanguage.CA to "Esborra cerca", AppLanguage.EU to "Garbitu bilaketa", AppLanguage.GL to "Borrar busca"),
  "Usa el buscador de arriba para elegir una estación y asignarla." to mapOf(AppLanguage.EN to "Use the search field above to choose and assign a station.", AppLanguage.CA to "Fes servir el cercador de dalt per escollir una estació i assignar-la.", AppLanguage.EU to "Erabili goiko bilatzailea geltoki bat aukeratu eta esleitzeko.", AppLanguage.GL to "Usa o buscador de enriba para escoller unha estación e asignala."),
  "La búsqueda actual apunta a %s. Se usará para %s si pulsas asignar." to mapOf(AppLanguage.EN to "The current search points to %s. It will be used for %s if you tap assign.", AppLanguage.CA to "La cerca actual apunta a %s. Es farà servir per a %s si toques assignar.", AppLanguage.EU to "Uneko bilaketak %s seinalatzen du. %s-rako erabiliko da esleitu sakatzen baduzu.", AppLanguage.GL to "A busca actual apunta a %s. Usarase para %s se pulsas asignar."),
  "Asignar búsqueda" to mapOf(AppLanguage.EN to "Assign search", AppLanguage.CA to "Assigna cerca", AppLanguage.EU to "Esleitu bilaketa", AppLanguage.GL to "Asignar busca"),
  "Todavía no has fijado una estación para %s." to mapOf(AppLanguage.EN to "You haven't pinned a station for %s yet.", AppLanguage.CA to "Encara no has fixat una estació per a %s.", AppLanguage.EU to "Oraindik ez duzu geltokirik finkatu %s-rako.", AppLanguage.GL to "Aínda non fixaches unha estación para %s."),
  "Se comprueba cada 30 s. Notificación si la estación se llena." to mapOf(AppLanguage.EN to "Checked every 30 s. Notification if the station fills up.", AppLanguage.CA to "Es comprova cada 30 s. Notificació si l'estació s'omple.", AppLanguage.EU to "30 segundoero egiaztatzen da. Jakinarazpena geltokia betetzen bada.", AppLanguage.GL to "Compróbase cada 30 s. Notificación se a estación se enche."),
  "Tiempo restante: %s" to mapOf(AppLanguage.EN to "Time remaining: %s", AppLanguage.CA to "Temps restant: %s", AppLanguage.EU to "Geratzen den denbora: %s", AppLanguage.GL to "Tempo restante: %s"),
  "Vigilancia activa" to mapOf(AppLanguage.EN to "Monitoring active", AppLanguage.CA to "Vigilància activa", AppLanguage.EU to "Zaintza aktiboa", AppLanguage.GL to "Vixilancia activa"),
  "Iniciar vigilancia" to mapOf(AppLanguage.EN to "Start monitoring", AppLanguage.CA to "Inicia la vigilància", AppLanguage.EU to "Hasi zaintza", AppLanguage.GL to "Iniciar vixilancia"),
  "Recibirás una notificación si se llena antes de que llegues." to mapOf(AppLanguage.EN to "You'll get a notification if it fills up before you arrive.", AppLanguage.CA to "Rebràs una notificació si s'omple abans que arribis.", AppLanguage.EU to "Jakinarazpen bat jasoko duzu heldu aurretik betetzen bada.", AppLanguage.GL to "Recibirás unha notificación se se enche antes de que chegues."),
  "Vigilar esta estación" to mapOf(AppLanguage.EN to "Monitor this station", AppLanguage.CA to "Vigila aquesta estació", AppLanguage.EU to "Zaindu geltoki hau", AppLanguage.GL to "Vixiar esta estación"),
  "Buscando estación cercana..." to mapOf(AppLanguage.EN to "Searching nearby station...", AppLanguage.CA to "Buscant estació propera...", AppLanguage.EU to "Gertuko geltokia bilatzen...", AppLanguage.GL to "Buscando estación próxima..."),
  "Sugerencias" to mapOf(AppLanguage.EN to "Suggestions", AppLanguage.CA to "Suggeriments", AppLanguage.EU to "Iradokizunak", AppLanguage.GL to "Suxestións"),
  "Toca el mapa para elegir destino" to mapOf(AppLanguage.EN to "Tap the map to pick a destination", AppLanguage.CA to "Toca el mapa per escollir el destí", AppLanguage.EU to "Ukitu mapa helmuga hautatzeko", AppLanguage.GL to "Toca o mapa para escoller destino"),
  "Elegir en mapa" to mapOf(AppLanguage.EN to "Pick on map", AppLanguage.CA to "Escull al mapa", AppLanguage.EU to "Hautatu mapan", AppLanguage.GL to "Escoller no mapa"),
  "Cancelar mapa" to mapOf(AppLanguage.EN to "Cancel map", AppLanguage.CA to "Cancel·la mapa", AppLanguage.EU to "Utzi mapa", AppLanguage.GL to "Cancelar mapa"),
  "Borrar" to mapOf(AppLanguage.EN to "Clear", AppLanguage.CA to "Esborra", AppLanguage.EU to "Garbitu", AppLanguage.GL to "Borrar"),
  "Escribe una dirección o lugar" to mapOf(AppLanguage.EN to "Type an address or place", AppLanguage.CA to "Escriu una adreça o lloc", AppLanguage.EU to "Idatzi helbide edo leku bat", AppLanguage.GL to "Escribe un enderezo ou lugar"),
  "Novedades" to mapOf(AppLanguage.EN to "What's new", AppLanguage.CA to "Novetats", AppLanguage.EU to "Berritasunak", AppLanguage.GL to "Novidades"),
  "No hay datos de estaciones disponibles." to mapOf(AppLanguage.EN to "No station data available.", AppLanguage.CA to "No hi ha dades d'estacions disponibles.", AppLanguage.EU to "Ez dago geltokien daturik erabilgarri.", AppLanguage.GL to "Non hai datos de estacións dispoñibles."),
  "Bici Radar" to mapOf(AppLanguage.EN to "Bici Radar", AppLanguage.CA to "Bici Radar", AppLanguage.EU to "Bici Radar", AppLanguage.GL to "Bici Radar"),
  "Cerca" to mapOf(AppLanguage.EN to "Nearby", AppLanguage.CA to "A prop", AppLanguage.EU to "Gertu", AppLanguage.GL to "Preto"),
  "Mapa" to mapOf(AppLanguage.EN to "Map", AppLanguage.CA to "Mapa", AppLanguage.EU to "Mapa", AppLanguage.GL to "Mapa"),
  "Favoritos" to mapOf(AppLanguage.EN to "Favorites", AppLanguage.CA to "Favorits", AppLanguage.EU to "Gogokoak", AppLanguage.GL to "Favoritas"),
  "Viaje" to mapOf(AppLanguage.EN to "Trip", AppLanguage.CA to "Viatge", AppLanguage.EU to "Bidaia", AppLanguage.GL to "Viaxe"),
  "Ajustes" to mapOf(AppLanguage.EN to "Settings", AppLanguage.CA to "Ajustos", AppLanguage.EU to "Ezarpenak", AppLanguage.GL to "Axustes"),
  "Bicis + Huecos" to mapOf(AppLanguage.EN to "Bikes + Slots", AppLanguage.CA to "Bicis + Ancoratges", AppLanguage.EU to "Bizikletak + Lekuak", AppLanguage.GL to "Bicis + Ocos"),
  "Solo bicis" to mapOf(AppLanguage.EN to "Bikes only", AppLanguage.CA to "Només bicis", AppLanguage.EU to "Bizikletak bakarrik", AppLanguage.GL to "Só bicis"),
  "Solo huecos" to mapOf(AppLanguage.EN to "Slots only", AppLanguage.CA to "Només ancoratges", AppLanguage.EU to "Lekuak bakarrik", AppLanguage.GL to "Só ocos"),
  "Tema oscuro" to mapOf(AppLanguage.EN to "Dark theme", AppLanguage.CA to "Tema fosc", AppLanguage.EU to "Gai iluna", AppLanguage.GL to "Tema escuro"),
  "La app se adapta automáticamente al modo oscuro del sistema." to mapOf(AppLanguage.EN to "The app now adapts automatically to the system dark mode.", AppLanguage.CA to "L'app s'adapta automàticament al mode fosc del sistema.", AppLanguage.EU to "Aplikazioa automatikoki moldatzen da sistemaren modu ilunera.", AppLanguage.GL to "A app adáptase automaticamente ao modo escuro do sistema."),
  "Tarjeta descartable" to mapOf(AppLanguage.EN to "Dismissible card", AppLanguage.CA to "Targeta descartable", AppLanguage.EU to "Txartel itxigarria", AppLanguage.GL to "Tarxeta descartable"),
  "Ahora puedes cerrar la tarjeta de estación en el mapa con el botón X." to mapOf(AppLanguage.EN to "You can now close the station card on the map with the X button.", AppLanguage.CA to "Ara pots tancar la targeta d'estació al mapa amb el botó X.", AppLanguage.EU to "Orain mapako geltoki txartela X botoiarekin itxi dezakezu.", AppLanguage.GL to "Agora podes pechar a tarxeta da estación no mapa co botón X."),
  "Filtros en el mapa" to mapOf(AppLanguage.EN to "Map filters", AppLanguage.CA to "Filtres al mapa", AppLanguage.EU to "Mapako iragazkiak", AppLanguage.GL to "Filtros no mapa"),
  "Filtra estaciones por disponibilidad: bicis + huecos, solo bicis o solo huecos." to mapOf(AppLanguage.EN to "Filter stations by availability: bikes + slots, bikes only, or slots only.", AppLanguage.CA to "Filtra estacions per disponibilitat: bicis + ancoratges, només bicis o només ancoratges.", AppLanguage.EU to "Iragazi geltokiak erabilgarritasunaren arabera: bizikletak + lekuak, bizikletak bakarrik edo lekuak bakarrik.", AppLanguage.GL to "Filtra estacións por dispoñibilidade: bicis + ocos, só bicis ou só ocos."),
  "Indicador de refresco" to mapOf(AppLanguage.EN to "Refresh indicator", AppLanguage.CA to "Indicador d'actualització", AppLanguage.EU to "Eguneratze adierazlea", AppLanguage.GL to "Indicador de actualización"),
  "Cuenta atrás visible junto al botón de refresco (actualización cada 5 min)." to mapOf(AppLanguage.EN to "Visible countdown next to the refresh button (updates every 5 min).", AppLanguage.CA to "Compte enrere visible al costat del botó d'actualització (cada 5 min).", AppLanguage.EU to "Atzerako kontaketa ikusgai freskatzeko botoiaren ondoan (5 minuturo eguneratzen da).", AppLanguage.GL to "Conta atrás visible xunto ao botón de actualización (cada 5 min)."),
  "Patrón de uso" to mapOf(AppLanguage.EN to "Usage pattern", AppLanguage.CA to "Patró d'ús", AppLanguage.EU to "Erabilera eredua", AppLanguage.GL to "Patrón de uso"),
  "Gráfica con la media histórica de bicis por hora en cada estación (datos de datosbizi.com)." to mapOf(AppLanguage.EN to "Chart with the historical average number of bikes per hour at each station (data from datosbizi.com).", AppLanguage.CA to "Gràfic amb la mitjana històrica de bicis per hora a cada estació (dades de datosbizi.com).", AppLanguage.EU to "Geltoki bakoitzean orduko bizikleten batez besteko historikoa erakusten duen grafikoa (datosbizi.com datuekin).", AppLanguage.GL to "Gráfica coa media histórica de bicis por hora en cada estación (datos de datosbizi.com)."),
  "Cargando estaciones cercanas, favoritas y atajos..." to mapOf(AppLanguage.EN to "Loading nearby stations, favorites, and shortcuts...", AppLanguage.CA to "Carregant estacions properes, favorites i dreceres...", AppLanguage.EU to "Gertuko geltokiak, gogokoak eta lasterbideak kargatzen...", AppLanguage.GL to "Cargando estacións próximas, favoritas e atallos..."),
  "Preparando la experiencia del iPhone." to mapOf(AppLanguage.EN to "Preparing the iPhone experience.", AppLanguage.CA to "Preparant l'experiència de l'iPhone.", AppLanguage.EU to "iPhone esperientzia prestatzen.", AppLanguage.GL to "Preparando a experiencia no iPhone."),
  "Preparando la experiencia de Android." to mapOf(AppLanguage.EN to "Preparing the Android experience.", AppLanguage.CA to "Preparant l'experiència d'Android.", AppLanguage.EU to "Android esperientzia prestatzen.", AppLanguage.GL to "Preparando a experiencia en Android."),
  "Buscar estación o dirección" to mapOf(AppLanguage.EN to "Search station or address", AppLanguage.CA to "Cerca estació o adreça", AppLanguage.EU to "Bilatu geltokia edo helbidea", AppLanguage.GL to "Buscar estación ou enderezo"),
  "Mi ubicación" to mapOf(AppLanguage.EN to "My location", AppLanguage.CA to "La meva ubicació", AppLanguage.EU to "Nire kokapena", AppLanguage.GL to "A miña localización"),
  "No hemos podido actualizar el mapa" to mapOf(AppLanguage.EN to "We couldn't update the map", AppLanguage.CA to "No hem pogut actualitzar el mapa", AppLanguage.EU to "Ezin izan dugu mapa eguneratu", AppLanguage.GL to "Non puidemos actualizar o mapa"),
  "Reintentar" to mapOf(AppLanguage.EN to "Try again", AppLanguage.CA to "Torna-ho a provar", AppLanguage.EU to "Saiatu berriro", AppLanguage.GL to "Tentar de novo"),
  "Todavía no tenemos estaciones en pantalla" to mapOf(AppLanguage.EN to "We don't have stations on screen yet", AppLanguage.CA to "Encara no tenim estacions en pantalla", AppLanguage.EU to "Oraindik ez dugu geltokirik pantailan", AppLanguage.GL to "Aínda non temos estacións na pantalla"),
  "No hay estaciones para esa búsqueda" to mapOf(AppLanguage.EN to "No stations for that search", AppLanguage.CA to "No hi ha estacions per a aquesta cerca", AppLanguage.EU to "Ez dago bilaketa horretarako geltokirik", AppLanguage.GL to "Non hai estacións para esa busca"),
  "La app volverá a usar Zaragoza centro si la ubicación tarda demasiado o no está disponible." to mapOf(AppLanguage.EN to "The app will fall back to downtown Zaragoza if location takes too long or is unavailable.", AppLanguage.CA to "L'app tornarà a usar el centre de Saragossa si la ubicació triga massa o no està disponible.", AppLanguage.EU to "Aplikazioak Zaragozako erdigunea erabiliko du kokapena beranduegi badator edo eskuragarri ez badago.", AppLanguage.GL to "A app volverá usar o centro de Zaragoza se a localización tarda demasiado ou non está dispoñible."),
  "Prueba con otro nombre, dirección o número de estación." to mapOf(AppLanguage.EN to "Try another station name, address, or station number.", AppLanguage.CA to "Prova amb un altre nom, adreça o número d'estació.", AppLanguage.EU to "Saiatu beste izen, helbide edo geltoki zenbaki batekin.", AppLanguage.GL to "Proba con outro nome, enderezo ou número de estación."),
  "Cargar estaciones" to mapOf(AppLanguage.EN to "Load stations", AppLanguage.CA to "Carrega estacions", AppLanguage.EU to "Kargatu geltokiak", AppLanguage.GL to "Cargar estacións"),
  "Acciones rápidas para encontrar bicis, huecos y abrir rutas sin pasar por el mapa completo." to mapOf(AppLanguage.EN to "Quick actions to find bikes, slots, and open routes without going through the full map.", AppLanguage.CA to "Accions ràpides per trobar bicis, ancoratges i obrir rutes sense passar pel mapa complet.", AppLanguage.EU to "Ekintza azkarrak bizikletak eta lekuak aurkitzeko eta ibilbideak irekitzeko mapa osoa erabili gabe.", AppLanguage.GL to "Accións rápidas para atopar bicis, ocos e abrir rutas sen pasar polo mapa completo."),
  "Cerca de ti" to mapOf(AppLanguage.EN to "Near you", AppLanguage.CA to "A prop teu", AppLanguage.EU to "Zugandik gertu", AppLanguage.GL to "Preto de ti"),
  "Estaciones ordenadas por cercanía y acciones rápidas para moverte." to mapOf(AppLanguage.EN to "Stations sorted by distance and quick actions to get moving.", AppLanguage.CA to "Estacions ordenades per proximitat i accions ràpides per moure't.", AppLanguage.EU to "Gertutasunaren arabera ordenatutako geltokiak eta mugitzeko ekintza azkarrak.", AppLanguage.GL to "Estacións ordenadas por proximidade e accións rápidas para moverte."),
  "Más cercana con bicis" to mapOf(AppLanguage.EN to "Nearest with bikes", AppLanguage.CA to "Més propera amb bicis", AppLanguage.EU to "Bizikletadun hurbilena", AppLanguage.GL to "Máis próxima con bicis"),
  "Sin bicis cercanas" to mapOf(AppLanguage.EN to "No nearby bikes", AppLanguage.CA to "Sense bicis a prop", AppLanguage.EU to "Ez dago gertuko bizikletarik", AppLanguage.GL to "Sen bicis próximas"),
  "Más cercana con huecos" to mapOf(AppLanguage.EN to "Nearest with slots", AppLanguage.CA to "Més propera amb ancoratges", AppLanguage.EU to "Lekuak dituen hurbilena", AppLanguage.GL to "Máis próxima con ocos"),
  "Sin huecos cercanos" to mapOf(AppLanguage.EN to "No nearby slots", AppLanguage.CA to "Sense ancoratges a prop", AppLanguage.EU to "Ez dago gertuko lekurik", AppLanguage.GL to "Sen ocos próximos"),
  "Actualizando estaciones..." to mapOf(AppLanguage.EN to "Updating stations...", AppLanguage.CA to "Actualitzant estacions...", AppLanguage.EU to "Geltokiak eguneratzen...", AppLanguage.GL to "Actualizando estacións..."),
  "Estaciones cercanas" to mapOf(AppLanguage.EN to "Nearby stations", AppLanguage.CA to "Estacions properes", AppLanguage.EU to "Gertuko geltokiak", AppLanguage.GL to "Estacións próximas"),
  "Si no hay estaciones dentro del radio, te seguimos mostrando igualmente la más cercana." to mapOf(AppLanguage.EN to "If there are no stations inside the radius, we'll still show you the nearest one.", AppLanguage.CA to "Si no hi ha estacions dins del radi, igualment et mostrarem la més propera.", AppLanguage.EU to "Erradioaren barruan geltokirik ez badago, hala ere hurbilena erakutsiko dizugu.", AppLanguage.GL to "Se non hai estacións dentro do radio, igualmente mostrarémosche a máis próxima."),
  "Toca cualquier tarjeta para abrir el detalle, guardarla o lanzar la ruta." to mapOf(AppLanguage.EN to "Tap any card to open details, save it, or start the route.", AppLanguage.CA to "Toca qualsevol targeta per obrir el detall, desar-la o iniciar la ruta.", AppLanguage.EU to "Ukitu edozein txartel xehetasunak irekitzeko, gordetzeko edo ibilbidea abiatzeko.", AppLanguage.GL to "Toca calquera tarxeta para abrir o detalle, gardala ou iniciar a ruta."),
  "Actualizar estaciones" to mapOf(AppLanguage.EN to "Refresh stations", AppLanguage.CA to "Actualitza estacions", AppLanguage.EU to "Eguneratu geltokiak", AppLanguage.GL to "Actualizar estacións"),
  "Bicis y huecos" to mapOf(AppLanguage.EN to "Bikes and slots", AppLanguage.CA to "Bicis i ancoratges", AppLanguage.EU to "Bizikletak eta lekuak", AppLanguage.GL to "Bicis e ocos"),
  "Solo bicis o solo huecos" to mapOf(AppLanguage.EN to "Only bikes or only slots", AppLanguage.CA to "Només bicis o només ancoratges", AppLanguage.EU to "Bizikletak bakarrik edo lekuak bakarrik", AppLanguage.GL to "Só bicis ou só ocos"),
  "Sin servicio" to mapOf(AppLanguage.EN to "Out of service", AppLanguage.CA to "Sense servei", AppLanguage.EU to "Zerbitzurik gabe", AppLanguage.GL to "Sen servizo"),
  "No hay dentro de %s m" to mapOf(AppLanguage.EN to "None within %s m", AppLanguage.CA to "No n'hi ha dins de %s m", AppLanguage.EU to "%s m barruan ez dago", AppLanguage.GL to "Non hai dentro de %s m"),
  "Estación más cercana" to mapOf(AppLanguage.EN to "Nearest station", AppLanguage.CA to "Estació més propera", AppLanguage.EU to "Geltoki hurbilena", AppLanguage.GL to "Estación máis próxima"),
  "Estación seleccionada" to mapOf(AppLanguage.EN to "Selected station", AppLanguage.CA to "Estació seleccionada", AppLanguage.EU to "Hautatutako geltokia", AppLanguage.GL to "Estación seleccionada"),
  "Cerrar" to mapOf(AppLanguage.EN to "Close", AppLanguage.CA to "Tanca", AppLanguage.EU to "Itxi", AppLanguage.GL to "Pechar"),
  "La más cercana está a %s m · %s bicis · %s libres" to mapOf(AppLanguage.EN to "The nearest one is %s m away · %s bikes · %s free", AppLanguage.CA to "La més propera és a %s m · %s bicis · %s lliures", AppLanguage.EU to "Hurbilena %s m-ra dago · %s bizikleta · %s libre", AppLanguage.GL to "A máis próxima está a %s m · %s bicis · %s libres"),
  "%s m · %s bicis · %s libres" to mapOf(AppLanguage.EN to "%s m · %s bikes · %s free", AppLanguage.CA to "%s m · %s bicis · %s lliures", AppLanguage.EU to "%s m · %s bizikleta · %s libre", AppLanguage.GL to "%s m · %s bicis · %s libres"),
  "%s m" to mapOf(AppLanguage.EN to "%s m", AppLanguage.CA to "%s m", AppLanguage.EU to "%s m", AppLanguage.GL to "%s m"),
  "Ruta" to mapOf(AppLanguage.EN to "Route", AppLanguage.CA to "Ruta", AppLanguage.EU to "Ibilbidea", AppLanguage.GL to "Ruta"),
  "Guardada" to mapOf(AppLanguage.EN to "Saved", AppLanguage.CA to "Desada", AppLanguage.EU to "Gordeta", AppLanguage.GL to "Gardada"),
  "Guardar" to mapOf(AppLanguage.EN to "Save", AppLanguage.CA to "Desa", AppLanguage.EU to "Gorde", AppLanguage.GL to "Gardar"),
  "Detalle" to mapOf(AppLanguage.EN to "Details", AppLanguage.CA to "Detall", AppLanguage.EU to "Xehetasuna", AppLanguage.GL to "Detalle"),
  "Tus estaciones guardadas para consultar el estado o abrir una ruta con un toque." to mapOf(AppLanguage.EN to "Your saved stations to check status or open a route with one tap.", AppLanguage.CA to "Les teves estacions desades per consultar l'estat o obrir una ruta amb un toc.", AppLanguage.EU to "Gordetako geltokiak egoera ikusteko edo ibilbidea ukitu bakarrean irekitzeko.", AppLanguage.GL to "As túas estacións gardadas para consultar o estado ou abrir unha ruta cun toque."),
  "Mis estaciones" to mapOf(AppLanguage.EN to "My stations", AppLanguage.CA to "Les meves estacions", AppLanguage.EU to "Nire geltokiak", AppLanguage.GL to "As miñas estacións"),
  "Buscar estación para fijarla o filtrar favoritas" to mapOf(AppLanguage.EN to "Search a station to pin or filter favorites", AppLanguage.CA to "Cerca una estació per fixar-la o filtrar favorites", AppLanguage.EU to "Bilatu geltoki bat finkatzeko edo gogokoak iragazteko", AppLanguage.GL to "Buscar unha estación para fixala ou filtrar favoritas"),
  "Casa y trabajo" to mapOf(AppLanguage.EN to "Home and work", AppLanguage.CA to "Casa i feina", AppLanguage.EU to "Etxea eta lana", AppLanguage.GL to "Casa e traballo"),
  "Puedes fijar Casa o Trabajo desde el buscador o directamente desde una favorita. Desliza una favorita para quitarla." to mapOf(AppLanguage.EN to "You can pin Home or Work from the search field or directly from a favorite. Swipe a favorite to remove it.", AppLanguage.CA to "Pots fixar Casa o Feina des del cercador o directament des d'una favorita. Llisca una favorita per eliminar-la.", AppLanguage.EU to "Etxea edo Lana bilatzailetik edo zuzenean gogoko batetik finka ditzakezu. Irristatu gogoko bat kentzeko.", AppLanguage.GL to "Podes fixar Casa ou Traballo desde a busca ou directamente desde unha favorita. Desliza unha favorita para quitala."),
  "Casa" to mapOf(AppLanguage.EN to "Home", AppLanguage.CA to "Casa", AppLanguage.EU to "Etxea", AppLanguage.GL to "Casa"),
  "Trabajo" to mapOf(AppLanguage.EN to "Work", AppLanguage.CA to "Feina", AppLanguage.EU to "Lana", AppLanguage.GL to "Traballo"),
  "Todavía no tienes favoritas" to mapOf(AppLanguage.EN to "You don't have favorites yet", AppLanguage.CA to "Encara no tens favorites", AppLanguage.EU to "Oraindik ez duzu gogokorik", AppLanguage.GL to "Aínda non tes favoritas"),
  "Guarda estaciones desde el mapa para consultarlas más rápido y compartirlas con el reloj." to mapOf(AppLanguage.EN to "Save stations from the map to check them faster and share them with the watch.", AppLanguage.CA to "Desa estacions des del mapa per consultar-les més ràpid i compartir-les amb el rellotge.", AppLanguage.EU to "Gorde geltokiak mapatik azkarrago kontsultatzeko eta erlojuarekin partekatzeko.", AppLanguage.GL to "Garda estacións desde o mapa para consultalas máis rápido e compartilas co reloxo."),
  "Personaliza la experiencia de la app y comparte feedback cuando quieras." to mapOf(AppLanguage.EN to "Customize the app experience and share feedback whenever you want.", AppLanguage.CA to "Personalitza l'experiència de l'app i comparteix comentaris quan vulguis.", AppLanguage.EU to "Pertsonalizatu aplikazioaren esperientzia eta partekatu iritzia nahi duzunean.", AppLanguage.GL to "Personaliza a experiencia da app e comparte comentarios cando queiras."),
  "Radio para estación cercana" to mapOf(AppLanguage.EN to "Nearby station radius", AppLanguage.CA to "Radi per a l'estació propera", AppLanguage.EU to "Gertuko geltokiaren erradioa", AppLanguage.GL to "Radio para estación próxima"),
  "Si no hay estaciones dentro del radio, la app mostrará igualmente la más cercana y te indicará la distancia." to mapOf(AppLanguage.EN to "If there are no stations inside the radius, the app will still show the nearest one and its distance.", AppLanguage.CA to "Si no hi ha estacions dins del radi, l'app igualment mostrarà la més propera i n'indicarà la distància.", AppLanguage.EU to "Erradio barruan geltokirik ez badago, aplikazioak hurbilena erakutsiko du eta distantzia adieraziko dizu.", AppLanguage.GL to "Se non hai estacións dentro do radio, a app mostrará igualmente a máis próxima e indicarache a distancia."),
  "%s m activo" to mapOf(AppLanguage.EN to "%s m active", AppLanguage.CA to "%s m actiu", AppLanguage.EU to "%s m aktibo", AppLanguage.GL to "%s m activo"),
  "Atajos" to mapOf(AppLanguage.EN to "Shortcuts", AppLanguage.CA to "Dreceres", AppLanguage.EU to "Lasterbideak", AppLanguage.GL to "Atallos"),
  "Consulta todos los comandos de voz disponibles y cómo invocarlos con %s." to mapOf(AppLanguage.EN to "Review all available voice commands and how to invoke them with %s.", AppLanguage.CA to "Consulta totes les ordres de veu disponibles i com invocar-les amb %s.", AppLanguage.EU to "%s erabilita erabilgarri dauden ahots komando guztiak eta nola deitu ikusi.", AppLanguage.GL to "Consulta todos os comandos de voz dispoñibles e como invocalos con %s."),
  "Abrir guía de atajos" to mapOf(AppLanguage.EN to "Open shortcuts guide", AppLanguage.CA to "Obre la guia de dreceres", AppLanguage.EU to "Ireki lasterbideen gida", AppLanguage.GL to "Abrir guía de atallos"),
  "Apariencia" to mapOf(AppLanguage.EN to "Appearance", AppLanguage.CA to "Aparença", AppLanguage.EU to "Itxura", AppLanguage.GL to "Aparencia"),
  "Elige si la app sigue el sistema o usa siempre el tema claro u oscuro." to mapOf(AppLanguage.EN to "Choose whether the app follows the system or always uses the light or dark theme.", AppLanguage.CA to "Tria si l'app segueix el sistema o sempre fa servir el tema clar o fosc.", AppLanguage.EU to "Aukeratu aplikazioak sistemari jarraitzen dion edo beti gai argia edo iluna erabiltzen duen.", AppLanguage.GL to "Escolle se a app segue o sistema ou usa sempre o tema claro ou escuro."),
  "Sistema" to mapOf(AppLanguage.EN to "System", AppLanguage.CA to "Sistema", AppLanguage.EU to "Sistema", AppLanguage.GL to "Sistema"),
  "Claro" to mapOf(AppLanguage.EN to "Light", AppLanguage.CA to "Clar", AppLanguage.EU to "Argia", AppLanguage.GL to "Claro"),
  "Oscuro" to mapOf(AppLanguage.EN to "Dark", AppLanguage.CA to "Fosc", AppLanguage.EU to "Iluna", AppLanguage.GL to "Escuro"),
  "App de rutas en iPhone" to mapOf(AppLanguage.EN to "iPhone routing app", AppLanguage.CA to "App de rutes a l'iPhone", AppLanguage.EU to "iPhoneko ibilbide aplikazioa", AppLanguage.GL to "App de rutas no iPhone"),
  "Elige qué app abrir para las rutas rápidas, el detalle de estación y los atajos de Siri." to mapOf(AppLanguage.EN to "Choose which app opens for quick routes, station details, and Siri shortcuts.", AppLanguage.CA to "Tria quina app obrir per a les rutes ràpides, el detall d'estació i les dreceres de Siri.", AppLanguage.EU to "Aukeratu zein aplikazio ireki ibilbide azkarrentzat, geltoki xehetasunarentzat eta Siriren lasterbideentzat.", AppLanguage.GL to "Escolle que app abrir para as rutas rápidas, o detalle da estación e os atallos de Siri."),
  "Si Google Maps no está instalado, Bici Radar usará Apple Maps como fallback." to mapOf(AppLanguage.EN to "If Google Maps isn't installed, Bici Radar will fall back to Apple Maps.", AppLanguage.CA to "Si Google Maps no està instal·lat, Bici Radar usarà Apple Maps com a alternativa.", AppLanguage.EU to "Google Maps instalatuta ez badago, Bici Radarrek Apple Maps erabiliko du ordezko gisa.", AppLanguage.GL to "Se Google Maps non está instalado, Bici Radar usará Apple Maps como alternativa."),
  "Comentarios y sugerencias" to mapOf(AppLanguage.EN to "Feedback and suggestions", AppLanguage.CA to "Comentaris i suggeriments", AppLanguage.EU to "Iruzkinak eta iradokizunak", AppLanguage.GL to "Comentarios e suxestións"),
  "¿Algo no funciona bien o tienes una idea? Usa el formulario para enviar tu opinión." to mapOf(AppLanguage.EN to "If something isn't working well or you have an idea, use the form to send feedback.", AppLanguage.CA to "Si alguna cosa no funciona bé o tens una idea, usa el formulari per enviar la teva opinió.", AppLanguage.EU to "Zerbait ondo ez badabil edo ideia bat baduzu, erabili formularioa zure iritzia bidaltzeko.", AppLanguage.GL to "Se algo non funciona ben ou tes unha idea, usa o formulario para enviar a túa opinión."),
  "Abrir formulario de feedback" to mapOf(AppLanguage.EN to "Open feedback form", AppLanguage.CA to "Obre el formulari de comentaris", AppLanguage.EU to "Ireki iritzi formularioa", AppLanguage.GL to "Abrir formulario de comentarios"),
  "Privacidad y datos" to mapOf(AppLanguage.EN to "Privacy and data", AppLanguage.CA to "Privacitat i dades", AppLanguage.EU to "Pribatutasuna eta datuak", AppLanguage.GL to "Privacidade e datos"),
  "Consulta cómo gestiona Bici Radar la ubicación, los datos de uso y los accesos del dispositivo." to mapOf(AppLanguage.EN to "See how Bici Radar handles location, usage data, and device permissions.", AppLanguage.CA to "Consulta com gestiona Bici Radar la ubicació, les dades d'ús i els accessos del dispositiu.", AppLanguage.EU to "Ikusi Bici Radarrek nola kudeatzen dituen kokapena, erabilera datuak eta gailuaren baimenak.", AppLanguage.GL to "Consulta como xestiona Bici Radar a localización, os datos de uso e os accesos do dispositivo."),
  "Abrir política de privacidad" to mapOf(AppLanguage.EN to "Open privacy policy", AppLanguage.CA to "Obre la política de privacitat", AppLanguage.EU to "Ireki pribatutasun politika", AppLanguage.GL to "Abrir política de privacidade"),
  "Volver" to mapOf(AppLanguage.EN to "Back", AppLanguage.CA to "Tornar", AppLanguage.EU to "Itzuli", AppLanguage.GL to "Volver"),
  "Consulta qué puedes pedirle a Siri y cómo invocarlo de forma natural en Bici Radar." to mapOf(AppLanguage.EN to "See what you can ask Siri and how to invoke it naturally in Bici Radar.", AppLanguage.CA to "Consulta què pots demanar a Siri i com invocar-ho de manera natural a Bici Radar.", AppLanguage.EU to "Ikusi zer eska diezaiokezun Siriri eta nola deitu modu naturalean Bici Radar-en.", AppLanguage.GL to "Consulta que lle podes pedir a Siri e como invocalo de xeito natural en Bici Radar."),
  "Cómo invocarlos" to mapOf(AppLanguage.EN to "How to invoke them", AppLanguage.CA to "Com invocar-los", AppLanguage.EU to "Nola deitu", AppLanguage.GL to "Como invocalos"),
  "Estas acciones quedan disponibles en Siri y Atajos." to mapOf(AppLanguage.EN to "These actions are available in Siri and Shortcuts.", AppLanguage.CA to "Aquestes accions estan disponibles a Siri i Dreceres.", AppLanguage.EU to "Ekintza hauek Siri eta Lasterbideetan daude erabilgarri.", AppLanguage.GL to "Estas accións están dispoñibles en Siri e Atallos."),
  "Qué puedes pedirle a %s y cómo invocarlo dentro de Bici Radar." to mapOf(AppLanguage.EN to "What you can ask %s and how to invoke it inside Bici Radar.", AppLanguage.CA to "Què pots demanar a %s i com invocar-ho dins de Bici Radar.", AppLanguage.EU to "%s-i zer eska diezaiokezun eta Bici Radar barruan nola deitu.", AppLanguage.GL to "Que lle podes pedir a %s e como invocalo dentro de Bici Radar."),
  "Abre Siri o Atajos y usa frases naturales como las de abajo terminando en “con Bici Radar”." to mapOf(AppLanguage.EN to "Open Siri or Shortcuts and use natural phrases like the ones below ending with 'with Bici Radar'.", AppLanguage.CA to "Obre Siri o Dreceres i fes servir frases naturals com les de sota acabant amb 'amb Bici Radar'.", AppLanguage.EU to "Ireki Siri edo Lasterbideak eta erabili behekoen moduko esaldi naturalak amaieran 'Bici Radarrekin' esanez.", AppLanguage.GL to "Abre Siri ou Atallos e usa frases naturais como as de abaixo rematando con 'con Bici Radar'."),
  "Abre Google Assistant y prueba frases naturales como las de abajo. Si hace falta, añade “con Bici Radar” para desambiguar." to mapOf(AppLanguage.EN to "Open Google Assistant and try natural phrases like the ones below. If needed, add 'with Bici Radar' to disambiguate.", AppLanguage.CA to "Obre Google Assistant i prova frases naturals com les de sota. Si cal, afegeix 'amb Bici Radar' per desambiguar.", AppLanguage.EU to "Ireki Google Assistant eta probatu behekoen moduko esaldi naturalak. Beharrezkoa bada, gehitu 'Bici Radarrekin' argitzeko.", AppLanguage.GL to "Abre Google Assistant e proba frases naturais como as de abaixo. Se fai falla, engade 'con Bici Radar' para desambiguar."),
  "Radio actual para búsquedas cercanas: %s m." to mapOf(AppLanguage.EN to "Current radius for nearby searches: %s m.", AppLanguage.CA to "Radi actual per a cerques properes: %s m.", AppLanguage.EU to "Gertuko bilaketen uneko erradioa: %s m.", AppLanguage.GL to "Radio actual para buscas próximas: %s m."),
  "Última respuesta" to mapOf(AppLanguage.EN to "Latest answer", AppLanguage.CA to "Última resposta", AppLanguage.EU to "Azken erantzuna", AppLanguage.GL to "Última resposta"),
  "Distancia" to mapOf(AppLanguage.EN to "Distance", AppLanguage.CA to "Distància", AppLanguage.EU to "Distantzia", AppLanguage.GL to "Distancia"),
  "Fuente" to mapOf(AppLanguage.EN to "Source", AppLanguage.CA to "Font", AppLanguage.EU to "Iturria", AppLanguage.GL to "Fonte"),
  "Guardar esta estación" to mapOf(AppLanguage.EN to "Save this station", AppLanguage.CA to "Desa aquesta estació", AppLanguage.EU to "Gorde geltoki hau", AppLanguage.GL to "Gardar esta estación"),
  "Márcala como favorita o fíjala como Casa o Trabajo para recuperarla más rápido desde Favoritas y con los atajos de voz." to mapOf(AppLanguage.EN to "Mark it as a favorite or pin it as Home or Work to get back to it faster from Favorites and voice shortcuts.", AppLanguage.CA to "Marca-la com a favorita o fixa-la com a Casa o Feina per recuperar-la més ràpid des de Favorits i amb dreceres de veu.", AppLanguage.EU to "Markatu gogoko gisa edo finkatu Etxea edo Lana gisa Gogokoetatik eta ahots lasterbidetatik azkarrago berreskuratzeko.", AppLanguage.GL to "Márcaa como favorita ou fíxaa como Casa ou Traballo para recuperala máis rápido desde Favoritas e cos atallos de voz."),
  "Favorita" to mapOf(AppLanguage.EN to "Favorite", AppLanguage.CA to "Favorita", AppLanguage.EU to "Gogokoa", AppLanguage.GL to "Favorita"),
  "Ahora mismo esta estación está marcada como Casa y Trabajo." to mapOf(AppLanguage.EN to "This station is currently marked as Home and Work.", AppLanguage.CA to "Aquesta estació està marcada ara mateix com a Casa i Feina.", AppLanguage.EU to "Geltoki hau une honetan Etxea eta Lana gisa markatuta dago.", AppLanguage.GL to "Esta estación está agora marcada como Casa e Traballo."),
  "Ahora mismo esta estación está marcada como Casa." to mapOf(AppLanguage.EN to "This station is currently marked as Home.", AppLanguage.CA to "Aquesta estació està marcada ara mateix com a Casa.", AppLanguage.EU to "Geltoki hau une honetan Etxea gisa markatuta dago.", AppLanguage.GL to "Esta estación está agora marcada como Casa."),
  "Ahora mismo esta estación está marcada como Trabajo." to mapOf(AppLanguage.EN to "This station is currently marked as Work.", AppLanguage.CA to "Aquesta estació està marcada ara mateix com a Feina.", AppLanguage.EU to "Geltoki hau une honetan Lana gisa markatuta dago.", AppLanguage.GL to "Esta estación está agora marcada como Traballo."),
  "Puedes tocar Casa o Trabajo para asignarla directamente." to mapOf(AppLanguage.EN to "You can tap Home or Work to assign it directly.", AppLanguage.CA to "Pots tocar Casa o Feina per assignar-la directament.", AppLanguage.EU to "Etxea edo Lana uki dezakezu zuzenean esleitzeko.", AppLanguage.GL to "Podes tocar Casa ou Traballo para asignala directamente."),
  "Bicis" to mapOf(AppLanguage.EN to "Bikes", AppLanguage.CA to "Bicis", AppLanguage.EU to "Bizikletak", AppLanguage.GL to "Bicis"),
  "Huecos" to mapOf(AppLanguage.EN to "Slots", AppLanguage.CA to "Ancoratges", AppLanguage.EU to "Lekuak", AppLanguage.GL to "Ocos"),
  "Abrir ruta" to mapOf(AppLanguage.EN to "Open route", AppLanguage.CA to "Obre la ruta", AppLanguage.EU to "Ireki ibilbidea", AppLanguage.GL to "Abrir ruta"),
  "Quitar de favoritos" to mapOf(AppLanguage.EN to "Remove from favorites", AppLanguage.CA to "Treu de favorits", AppLanguage.EU to "Kendu gogokoetatik", AppLanguage.GL to "Quitar de favoritas"),
  "Guardar en favoritos" to mapOf(AppLanguage.EN to "Save to favorites", AppLanguage.CA to "Desa a favorits", AppLanguage.EU to "Gorde gogokoetan", AppLanguage.GL to "Gardar en favoritas"),
  "No hay datos de patrón disponibles" to mapOf(AppLanguage.EN to "No usage pattern data available", AppLanguage.CA to "No hi ha dades de patró disponibles", AppLanguage.EU to "Ez dago erabilera ereduen daturik", AppLanguage.GL to "Non hai datos de patrón dispoñibles"),
  "No hay datos para este tipo de día" to mapOf(AppLanguage.EN to "No data for this day type", AppLanguage.CA to "No hi ha dades per a aquest tipus de dia", AppLanguage.EU to "Ez dago daturik egun mota honetarako", AppLanguage.GL to "Non hai datos para este tipo de día"),
  "Media de bicis disponibles en esta estación según la hora del día, basada en datos históricos de datosbizi.com." to mapOf(AppLanguage.EN to "Average bikes available at this station by time of day, based on historical data from datosbizi.com.", AppLanguage.CA to "Mitjana de bicis disponibles en aquesta estació segons l'hora del dia, basada en dades històriques de datosbizi.com.", AppLanguage.EU to "Eguneko orduaren arabera geltoki honetan erabilgarri dauden bizikleten batez bestekoa, datosbizi.com-eko datu historikoetan oinarrituta.", AppLanguage.GL to "Media de bicis dispoñibles nesta estación segundo a hora do día, baseada en datos históricos de datosbizi.com."),
  "Más bicis" to mapOf(AppLanguage.EN to "Most bikes", AppLanguage.CA to "Més bicis", AppLanguage.EU to "Bizikleta gehien", AppLanguage.GL to "Máis bicis"),
  "Más huecos" to mapOf(AppLanguage.EN to "Most slots", AppLanguage.CA to "Més ancoratges", AppLanguage.EU to "Leku gehien", AppLanguage.GL to "Máis ocos"),
  "Parar vigilancia" to mapOf(AppLanguage.EN to "Stop monitoring", AppLanguage.CA to "Atura la vigilància", AppLanguage.EU to "Gelditu zaintza", AppLanguage.GL to "Deter vixilancia"),
  "No hemos podido buscar esa ubicación ahora mismo." to mapOf(AppLanguage.EN to "We couldn't search that location right now.", AppLanguage.CA to "No hem pogut cercar aquesta ubicació ara mateix.", AppLanguage.EU to "Ezin izan dugu kokapen hori bilatu une honetan.", AppLanguage.GL to "Non puidemos buscar esa localización neste momento."),
  "No hemos podido conectar con el servicio de localización." to mapOf(AppLanguage.EN to "We couldn't connect to the location service.", AppLanguage.CA to "No hem pogut connectar amb el servei de localització.", AppLanguage.EU to "Ezin izan dugu lokalizazio zerbitzuarekin konektatu.", AppLanguage.GL to "Non puidemos conectar co servizo de localización."),
  "Error de búsqueda: %s" to mapOf(AppLanguage.EN to "Search error: %s", AppLanguage.CA to "Error de cerca: %s", AppLanguage.EU to "Bilaketa errorea: %s", AppLanguage.GL to "Erro de busca: %s"),
  "desconocido" to mapOf(AppLanguage.EN to "unknown", AppLanguage.CA to "desconegut", AppLanguage.EU to "ezezaguna", AppLanguage.GL to "descoñecido"),
  "Pregunta por estaciones cercanas, favoritas o rutas." to mapOf(AppLanguage.EN to "Ask about nearby stations, favorites, or routes.", AppLanguage.CA to "Pregunta per estacions properes, favorites o rutes.", AppLanguage.EU to "Galdetu gertuko geltokiei, gogokoei edo ibilbideei buruz.", AppLanguage.GL to "Pregunta por estacións próximas, favoritas ou rutas."),
  "Busca la estación más cercana a tu destino y vigílala." to mapOf(AppLanguage.EN to "Find the nearest station to your destination and monitor it.", AppLanguage.CA to "Busca l'estació més propera al teu destí i vigila-la.", AppLanguage.EU to "Bilatu zure helmugatik hurbilen dagoen geltokia eta zaindu ezazu.", AppLanguage.GL to "Busca a estación máis próxima ao teu destino e vixíaa."),
  "Estación llena" to mapOf(AppLanguage.EN to "Station full", AppLanguage.CA to "Estacio plena", AppLanguage.EU to "Geltokia beteta", AppLanguage.GL to "Estación chea"),
  "\"%s\" ya no tiene plazas libres." to mapOf(AppLanguage.EN to "\"%s\" no longer has free slots.", AppLanguage.CA to "\"%s\" ja no te places lliures.", AppLanguage.EU to "\"%s\"-k ez du jada leku librerik.", AppLanguage.GL to "\"%s\" xa non ten ocos libres."),
  "Alternativa sugerida: %s%s — %s plazas." to mapOf(AppLanguage.EN to "Suggested alternative: %s%s — %s slots.", AppLanguage.CA to "Alternativa suggerida: %s%s — %s places.", AppLanguage.EU to "Iradokitako alternatiba: %s%s — %s leku.", AppLanguage.GL to "Alternativa suxerida: %s%s — %s prazas."),
  "No se encontró alternativa cercana con plazas." to mapOf(AppLanguage.EN to "No nearby alternative with free slots was found.", AppLanguage.CA to "No s'ha trobat cap alternativa propera amb places.", AppLanguage.EU to "Ez da gertuko alternatibarik aurkitu lekuekin.", AppLanguage.GL to "Non se atopou alternativa próxima con prazas."),
  "Entendido" to mapOf(AppLanguage.EN to "Got it", AppLanguage.CA to "Entes", AppLanguage.EU to "Ulertuta", AppLanguage.GL to "Entendido"),
  "¿Adónde vas?" to mapOf(AppLanguage.EN to "Where are you going?", AppLanguage.CA to "On vas?", AppLanguage.EU to "Nora zoaz?", AppLanguage.GL to "A onde vas?"),
  "Ruta a pie a %s" to mapOf(AppLanguage.EN to "Walking route to %s", AppLanguage.CA to "Ruta a peu cap a %s", AppLanguage.EU to "Oinezko ibilbidea %s-ra", AppLanguage.GL to "Ruta a pé ata %s"),
  "Estación sugerida" to mapOf(AppLanguage.EN to "Suggested station", AppLanguage.CA to "Estacio suggerida", AppLanguage.EU to "Iradokitako geltokia", AppLanguage.GL to "Estación suxerida"),
  "Plazas libres" to mapOf(AppLanguage.EN to "Free slots", AppLanguage.CA to "Places lliures", AppLanguage.EU to "Leku libreak", AppLanguage.GL to "Prazas libres"),
  "Quitar favorita" to mapOf(AppLanguage.EN to "Remove favorite", AppLanguage.CA to "Treure favorita", AppLanguage.EU to "Kendu gogokoa", AppLanguage.GL to "Quitar favorita"),
  "Eliminar favorita" to mapOf(AppLanguage.EN to "Delete favorite", AppLanguage.CA to "Eliminar favorita", AppLanguage.EU to "Ezabatu gogokoa", AppLanguage.GL to "Eliminar favorita"),
  "Encuentra la estación más cercana a tu ubicación actual y te abre la app en el contexto correcto." to mapOf(AppLanguage.EN to "Find the nearest station to your current location and open the app in the right context.", AppLanguage.CA to "Troba l'estació més propera a la teva ubicació actual i obre l'app en el context correcte.", AppLanguage.EU to "Bilatu zure uneko kokapenetik hurbilen dagoen geltokia eta ireki aplikazioa testuinguru egokian.", AppLanguage.GL to "Atopa a estación máis próxima á túa localización actual e abre a app no contexto correcto."),
  "Cuál es la estación más cercana con Bici Radar" to mapOf(AppLanguage.EN to "What's the nearest station with Bici Radar", AppLanguage.CA to "Quina es l'estacio mes propera amb Bici Radar", AppLanguage.EU to "Zein da geltoki hurbilena Bici Radarrekin", AppLanguage.GL to "Cal e a estación máis próxima con Bici Radar"),
  "Qué estación tengo más cerca con Bici Radar" to mapOf(AppLanguage.EN to "Which station is closest to me with Bici Radar", AppLanguage.CA to "Quina estacio tinc mes a prop amb Bici Radar", AppLanguage.EU to "Zein geltoki dut gertuen Bici Radarrekin", AppLanguage.GL to "Que estación teño máis preto con Bici Radar"),
  "Más cercana con bicis o huecos" to mapOf(AppLanguage.EN to "Nearest with bikes or slots", AppLanguage.CA to "Mes propera amb bicis o ancoratges", AppLanguage.EU to "Hurbilena bizikletekin edo lekuekin", AppLanguage.GL to "Máis próxima con bicis ou ocos"),
  "Busca la mejor estación cercana para coger bici o para devolverla con huecos libres." to mapOf(AppLanguage.EN to "Find the best nearby station to pick up or return a bike with free slots.", AppLanguage.CA to "Busca la millor estacio propera per agafar bici o tornar-la amb places lliures.", AppLanguage.EU to "Bilatu gertuko geltokirik onena bizikleta hartzeko edo itzultzeko leku libreekin.", AppLanguage.GL to "Busca a mellor estación próxima para coller ou devolver a bici con ocos libres."),
  "Dónde hay bicis cerca con Bici Radar" to mapOf(AppLanguage.EN to "Where are there bikes nearby with Bici Radar", AppLanguage.CA to "On hi ha bicis a prop amb Bici Radar", AppLanguage.EU to "Non daude bizikletak gertu Bici Radarrekin", AppLanguage.GL to "Onde hai bicis preto con Bici Radar"),
  "Dónde puedo dejar la bici con Bici Radar" to mapOf(AppLanguage.EN to "Where can I return the bike with Bici Radar", AppLanguage.CA to "On puc deixar la bici amb Bici Radar", AppLanguage.EU to "Non utz dezaket bizikleta Bici Radarrekin", AppLanguage.GL to "Onde podo deixar a bici con Bici Radar"),
  "Estado de una estación" to mapOf(AppLanguage.EN to "Station status", AppLanguage.CA to "Estat d'una estacio", AppLanguage.EU to "Geltoki baten egoera", AppLanguage.GL to "Estado dunha estación"),
  "Consulta una estación concreta por nombre, dirección, número o usando tus alias de Casa y Trabajo." to mapOf(AppLanguage.EN to "Check a specific station by name, address, number, or using your Home and Work aliases.", AppLanguage.CA to "Consulta una estacio concreta per nom, adreca, numero o fent servir els teus alias de Casa i Feina.", AppLanguage.EU to "Kontsultatu geltoki jakin bat izenaren, helbidearen, zenbakiaren edo Etxea eta Lana aliasak erabiliz.", AppLanguage.GL to "Consulta unha estación concreta por nome, enderezo, número ou usando os teus alias de Casa e Traballo."),
  "Cómo está casa con Bici Radar" to mapOf(AppLanguage.EN to "How is home with Bici Radar", AppLanguage.CA to "Com esta casa amb Bici Radar", AppLanguage.EU to "Nola dago etxea Bici Radarrekin", AppLanguage.GL to "Como está a casa con Bici Radar"),
  "Cuántas bicis hay en casa con Bici Radar" to mapOf(AppLanguage.EN to "How many bikes are at home with Bici Radar", AppLanguage.CA to "Quantes bicis hi ha a casa amb Bici Radar", AppLanguage.EU to "Zenbat bizikleta daude etxean Bici Radarrekin", AppLanguage.GL to "Cantas bicis hai na casa con Bici Radar"),
  "Cuántos huecos hay en la estación 48 con Bici Radar" to mapOf(AppLanguage.EN to "How many free slots are at station 48 with Bici Radar", AppLanguage.CA to "Quants ancoratges hi ha a l'estacio 48 amb Bici Radar", AppLanguage.EU to "Zenbat leku daude 48 geltokian Bici Radarrekin", AppLanguage.GL to "Cantos ocos hai na estación 48 con Bici Radar"),
  "Abre directamente tu lista de favoritas, con Casa y Trabajo incluidos cuando estén configurados." to mapOf(AppLanguage.EN to "Open your favorites list directly, including Home and Work when configured.", AppLanguage.CA to "Obre directament la teva llista de favorites, amb Casa i Feina incloses quan estiguin configurades.", AppLanguage.EU to "Ireki zuzenean zure gogokoen zerrenda, Etxea eta Lana barne konfiguratuta daudenean.", AppLanguage.GL to "Abre directamente a túa lista de favoritas, con Casa e Traballo incluídos cando estean configurados."),
  "Abre mis favoritas con Bici Radar" to mapOf(AppLanguage.EN to "Open my favorites with Bici Radar", AppLanguage.CA to "Obre les meves favorites amb Bici Radar", AppLanguage.EU to "Ireki nire gogokoak Bici Radarrekin", AppLanguage.GL to "Abre as miñas favoritas con Bici Radar"),
  "Cómo está trabajo con Bici Radar" to mapOf(AppLanguage.EN to "How is work with Bici Radar", AppLanguage.CA to "Com esta feina amb Bici Radar", AppLanguage.EU to "Nola dago lana Bici Radarrekin", AppLanguage.GL to "Como está o traballo con Bici Radar"),
  "Ruta a una estación" to mapOf(AppLanguage.EN to "Route to a station", AppLanguage.CA to "Ruta a una estacio", AppLanguage.EU to "Geltoki baterako ibilbidea", AppLanguage.GL to "Ruta a unha estación"),
  "Lanza la ruta rápida hacia una estación concreta o hacia Casa y Trabajo si ya los has configurado." to mapOf(AppLanguage.EN to "Launch the quick route to a specific station or to Home and Work if you've configured them.", AppLanguage.CA to "Inicia la ruta rapida cap a una estacio concreta o cap a Casa i Feina si ja les has configurades.", AppLanguage.EU to "Abiarazi ibilbide azkarra geltoki jakin batera edo Etxera eta Lanera dagoeneko konfiguratu badituzu.", AppLanguage.GL to "Inicia a ruta rápida cara a unha estación concreta ou cara a Casa e Traballo se xa os configuraches."),
  "Llévame a Plaza España con Bici Radar" to mapOf(AppLanguage.EN to "Take me to Plaza Espana with Bici Radar", AppLanguage.CA to "Porta'm a Placa Espanya amb Bici Radar", AppLanguage.EU to "Eraman nazazu Plaza Espanara Bici Radarrekin", AppLanguage.GL to "Lévame a Praza España con Bici Radar"),
  "Llévame al trabajo con Bici Radar" to mapOf(AppLanguage.EN to "Take me to work with Bici Radar", AppLanguage.CA to "Porta'm a la feina amb Bici Radar", AppLanguage.EU to "Eraman nazazu lanera Bici Radarrekin", AppLanguage.GL to "Lévame ao traballo con Bici Radar"),
  "No se encontró ninguna estación con plazas libres cerca." to mapOf(AppLanguage.EN to "No nearby station with free slots was found.", AppLanguage.CA to "No s'ha trobat cap estació propera amb places lliures.", AppLanguage.EU to "Ez da inguruan leku libreak dituen geltokirik aurkitu.", AppLanguage.GL to "Non se atopou ningunha estación próxima con ocos libres."),
  "Tienes %s estaciones guardadas en Bici Radar." to mapOf(AppLanguage.EN to "You have %s saved stations in Bici Radar.", AppLanguage.CA to "Tens %s estacions desades a Bici Radar.", AppLanguage.EU to "%s geltoki dituzu gordeta Bici Radar-en.", AppLanguage.GL to "Tes %s estacións gardadas en Bici Radar."),
  "No tengo datos de estaciones cercanas ahora mismo." to mapOf(AppLanguage.EN to "I don't have nearby station data right now.", AppLanguage.CA to "Ara mateix no tinc dades d'estacions properes.", AppLanguage.EU to "Une honetan ez dut gertuko geltokien daturik.", AppLanguage.GL to "Agora mesmo non teño datos de estacións próximas."),
  "La estación más cercana es %s con %s bicis y %s anclajes." to mapOf(AppLanguage.EN to "The nearest station is %s with %s bikes and %s docks.", AppLanguage.CA to "L'estació més propera és %s amb %s bicis i %s ancoratges.", AppLanguage.EU to "Geltoki hurbilena %s da, %s bizikleta eta %s ainguragailu ditu.", AppLanguage.GL to "A estación máis próxima é %s con %s bicis e %s ancoraxes."),
  "No he encontrado ninguna estación dentro de %s m. La más cercana está a %s m: %s, con %s bicis y %s anclajes." to mapOf(AppLanguage.EN to "I couldn't find any station within %s m. The nearest one is %s m away: %s, with %s bikes and %s docks.", AppLanguage.CA to "No he trobat cap estació dins de %s m. La més propera és a %s m: %s, amb %s bicis i %s ancoratges.", AppLanguage.EU to "Ez dut %s m barruan geltokirik aurkitu. Hurbilena %s m-ra dago: %s, %s bizikleta eta %s ainguragailurekin.", AppLanguage.GL to "Non atopei ningunha estación dentro de %s m. A máis próxima está a %s m: %s, con %s bicis e %s ancoraxes."),
  "No he encontrado estaciones cercanas con bicis disponibles ahora mismo." to mapOf(AppLanguage.EN to "I couldn't find nearby stations with available bikes right now.", AppLanguage.CA to "No he trobat estacions properes amb bicis disponibles ara mateix.", AppLanguage.EU to "Une honetan ez dut bizikleta erabilgarririk duen gertuko geltokirik aurkitu.", AppLanguage.GL to "Non atopei estacións próximas con bicis dispoñibles neste momento."),
  "La estación más cercana con bicis disponibles es %s con %s bicis y %s anclajes." to mapOf(AppLanguage.EN to "The nearest station with available bikes is %s with %s bikes and %s docks.", AppLanguage.CA to "L'estació més propera amb bicis disponibles és %s amb %s bicis i %s ancoratges.", AppLanguage.EU to "Bizikleta erabilgarriak dituen geltoki hurbilena %s da, %s bizikleta eta %s ainguragailurekin.", AppLanguage.GL to "A estación máis próxima con bicis dispoñibles é %s con %s bicis e %s ancoraxes."),
  "No he encontrado estaciones con bicis disponibles dentro de %s m. La más cercana está a %s m: %s, con %s bicis y %s anclajes." to mapOf(AppLanguage.EN to "I couldn't find stations with available bikes within %s m. The nearest one is %s m away: %s, with %s bikes and %s docks.", AppLanguage.CA to "No he trobat estacions amb bicis disponibles dins de %s m. La més propera és a %s m: %s, amb %s bicis i %s ancoratges.", AppLanguage.EU to "Ez dut %s m barruan bizikleta erabilgarririk duen geltokirik aurkitu. Hurbilena %s m-ra dago: %s, %s bizikleta eta %s ainguragailurekin.", AppLanguage.GL to "Non atopei estacións con bicis dispoñibles dentro de %s m. A máis próxima está a %s m: %s, con %s bicis e %s ancoraxes."),
  "No he encontrado estaciones cercanas con huecos libres ahora mismo." to mapOf(AppLanguage.EN to "I couldn't find nearby stations with free slots right now.", AppLanguage.CA to "No he trobat estacions properes amb ancoratges lliures ara mateix.", AppLanguage.EU to "Une honetan ez dut leku librerik duen gertuko geltokirik aurkitu.", AppLanguage.GL to "Non atopei estacións próximas con ocos libres neste momento."),
  "La estación más cercana con huecos libres es %s con %s huecos y %s bicis." to mapOf(AppLanguage.EN to "The nearest station with free slots is %s with %s slots and %s bikes.", AppLanguage.CA to "L'estació més propera amb ancoratges lliures és %s amb %s ancoratges i %s bicis.", AppLanguage.EU to "Leku libreak dituen geltoki hurbilena %s da, %s leku eta %s bizikletarekin.", AppLanguage.GL to "A estación máis próxima con ocos libres é %s con %s ocos e %s bicis."),
  "No he encontrado estaciones con huecos libres dentro de %s m. La más cercana está a %s m: %s, con %s huecos y %s bicis." to mapOf(AppLanguage.EN to "I couldn't find stations with free slots within %s m. The nearest one is %s m away: %s, with %s slots and %s bikes.", AppLanguage.CA to "No he trobat estacions amb ancoratges lliures dins de %s m. La més propera és a %s m: %s, amb %s ancoratges i %s bicis.", AppLanguage.EU to "Ez dut %s m barruan leku librerik duen geltokirik aurkitu. Hurbilena %s m-ra dago: %s, %s leku eta %s bizikletarekin.", AppLanguage.GL to "Non atopei estacións con ocos libres dentro de %s m. A máis próxima está a %s m: %s, con %s ocos e %s bicis."),
  "%s tiene %s bicis disponibles." to mapOf(AppLanguage.EN to "%s has %s bikes available.", AppLanguage.CA to "%s té %s bicis disponibles.", AppLanguage.EU to "%s-k %s bizikleta erabilgarri ditu.", AppLanguage.GL to "%s ten %s bicis dispoñibles."),
  "No he encontrado esa estación." to mapOf(AppLanguage.EN to "I couldn't find that station.", AppLanguage.CA to "No he trobat aquesta estació.", AppLanguage.EU to "Ez dut geltoki hori aurkitu.", AppLanguage.GL to "Non atopei esa estación."),
  "%s tiene %s huecos libres." to mapOf(AppLanguage.EN to "%s has %s free slots.", AppLanguage.CA to "%s té %s ancoratges lliures.", AppLanguage.EU to "%s-k %s leku libre ditu.", AppLanguage.GL to "%s ten %s ocos libres."),
  "Abriendo la ruta a la estación seleccionada." to mapOf(AppLanguage.EN to "Opening the route to the selected station.", AppLanguage.CA to "Obrint la ruta cap a l'estació seleccionada.", AppLanguage.EU to "Hautatutako geltokirako ibilbidea irekitzen.", AppLanguage.GL to "Abrindo a ruta cara á estación seleccionada."),
  "%s tiene %s bicis disponibles y %s huecos libres." to mapOf(AppLanguage.EN to "%s has %s bikes available and %s free slots.", AppLanguage.CA to "%s té %s bicis disponibles i %s ancoratges lliures.", AppLanguage.EU to "%s-k %s bizikleta erabilgarri eta %s leku libre ditu.", AppLanguage.GL to "%s ten %s bicis dispoñibles e %s ocos libres."),
  "Mapa no disponible. Configura una API key de Google Maps." to mapOf(AppLanguage.EN to "Map unavailable. Configure a Google Maps API key.", AppLanguage.CA to "Mapa no disponible. Configura una API key de Google Maps.", AppLanguage.EU to "Mapa ez dago erabilgarri. Konfiguratu Google Maps API key bat.", AppLanguage.GL to "Mapa non dispoñible. Configura unha API key de Google Maps."),
  "%s bicis · %s libres" to mapOf(AppLanguage.EN to "%s bikes · %s free", AppLanguage.CA to "%s bicis · %s lliures", AppLanguage.EU to "%s bizikleta · %s libre", AppLanguage.GL to "%s bicis · %s libres"),
  "%s bicis · %s huecos · %s m" to mapOf(AppLanguage.EN to "%s bikes · %s slots · %s m", AppLanguage.CA to "%s bicis · %s ancoratges · %s m", AppLanguage.EU to "%s bizikleta · %s leku · %s m", AppLanguage.GL to "%s bicis · %s ocos · %s m"),
  "Destino" to mapOf(AppLanguage.EN to "Destination", AppLanguage.CA to "Destinació", AppLanguage.EU to "Helmuga", AppLanguage.GL to "Destino"),
  "Vigilando estación Bizi…" to mapOf(AppLanguage.EN to "Monitoring Bizi station...", AppLanguage.CA to "Vigilant estació Bizi...", AppLanguage.EU to "Bizi geltokia zaintzen...", AppLanguage.GL to "Vixiando estación Bizi..."),
  "%s · %s free slot(s) · %s remaining" to mapOf(AppLanguage.ES to "%s · %s hueco(s) libre(s) · %s restante(s)", AppLanguage.EN to "%s · %s free slot(s) · %s remaining", AppLanguage.CA to "%s · %s ancoratge(s) lliure(s) · %s restant(s)", AppLanguage.EU to "%s · %s leku libre · %s geratzen dira", AppLanguage.GL to "%s · %s oco(s) libre(s) · %s restante(s)"),
  "Bizi Viaje" to mapOf(AppLanguage.EN to "Bizi Trip", AppLanguage.CA to "Bizi Viatge", AppLanguage.EU to "Bizi Bidaia", AppLanguage.GL to "Bizi Viaxe"),
  "Bizi Viaje (activo)" to mapOf(AppLanguage.EN to "Bizi Trip (active)", AppLanguage.CA to "Bizi Viatge (actiu)", AppLanguage.EU to "Bizi Bidaia (aktibo)", AppLanguage.GL to "Bizi Viaxe (activo)"),
  "Notificación persistente durante la monitorización de viaje" to mapOf(AppLanguage.EN to "Persistent notification while trip monitoring is active", AppLanguage.CA to "Notificació persistent durant la monitorització del viatge", AppLanguage.EU to "Jakinarazpen iraunkorra bidaia monitorizatzen den bitartean", AppLanguage.GL to "Notificación persistente durante a monitorización da viaxe"),
)

fun localizedText(key: String): String = localizedTextByKey[key]?.get(currentAppLanguage())
  ?: localizedTextByKey[key]?.get(AppLanguage.ES)
  ?: key

fun localizedText(key: String, vararg args: Any?): String {
  var result = localizedText(key)
  args.forEach { arg ->
    result = result.replaceFirst("%s", arg.toString())
  }
  return result
}

enum class SharedString(val fallback: String) {
  UNKNOWN_STATION("No he encontrado esa estación."),
  FAVORITE_COUNT("Tienes %s estaciones guardadas en Bici Radar."),
  NO_NEARBY_STATIONS("No tengo datos de estaciones cercanas ahora mismo."),
  NEAREST_STATION("La estación más cercana es %s con %s bicis y %s anclajes."),
  NEAREST_STATION_FALLBACK("No he encontrado ninguna estación dentro de %s m. La más cercana está a %s m: %s, con %s bicis y %s anclajes."),
  NO_NEARBY_BIKES("No he encontrado estaciones cercanas con bicis disponibles ahora mismo."),
  NEAREST_WITH_BIKES("La estación más cercana con bicis disponibles es %s con %s bicis y %s anclajes."),
  NEAREST_WITH_BIKES_FALLBACK("No he encontrado estaciones con bicis disponibles dentro de %s m. La más cercana está a %s m: %s, con %s bicis y %s anclajes."),
  NO_NEARBY_SLOTS("No he encontrado estaciones cercanas con huecos libres ahora mismo."),
  NEAREST_WITH_SLOTS("La estación más cercana con huecos libres es %s con %s huecos y %s bicis."),
  NEAREST_WITH_SLOTS_FALLBACK("No he encontrado estaciones con huecos libres dentro de %s m. La más cercana está a %s m: %s, con %s huecos y %s bicis."),
  STATION_BIKES("%s tiene %s bicis disponibles."),
  STATION_SLOTS("%s tiene %s huecos libres."),
  STATION_STATUS("%s tiene %s bicis disponibles y %s huecos libres."),
  ROUTE_TO_SELECTED_STATION("Abriendo la ruta a la estación seleccionada."),
  PATTERN_USAGE("Patrón de uso"),
  PATTERN_NO_DATA("No hay datos de patrón disponibles"),
  PATTERN_NO_DAY_TYPE_DATA("No hay datos para este tipo de día"),
  PATTERN_DESCRIPTION("Media de bicis disponibles en esta estación según la hora del día, basada en datos históricos de datosbizi.com."),
  PATTERN_MORE_BIKES("Más bicis"),
  PATTERN_MORE_SLOTS("Más huecos"),
  APP_NAME("Bici Radar"),
  SPLASH_LOADING_STATIONS("Cargando estaciones cercanas, favoritas y atajos..."),
  SPLASH_PREPARING_IPHONE("Preparando la experiencia del iPhone."),
  SPLASH_PREPARING_ANDROID("Preparando la experiencia de Android."),
  TAB_NEARBY("Cerca"),
  TAB_MAP("Mapa"),
  TAB_FAVORITES("Favoritos"),
  TAB_TRIP("Viaje"),
  TAB_SETTINGS("Ajustes"),
  MAP_FILTER_BIKES_AND_SLOTS("Bicis + Huecos"),
  MAP_FILTER_ONLY_BIKES("Solo bicis"),
  MAP_FILTER_ONLY_SLOTS("Solo huecos"),
  MAP_SEARCH_STATION_OR_ADDRESS("Buscar estación o dirección"),
  MAP_MY_LOCATION("Mi ubicación"),
  MAP_UPDATE_FAILED("No hemos podido actualizar el mapa"),
  RETRY("Reintentar"),
  MAP_NO_STATIONS_ON_SCREEN("Todavía no tenemos estaciones en pantalla"),
  MAP_NO_SEARCH_RESULTS("No hay estaciones para esa búsqueda"),
  MAP_LOCATION_FALLBACK_DESCRIPTION("La app volverá a usar Zaragoza centro si la ubicación tarda demasiado o no está disponible."),
  MAP_TRY_ANOTHER_QUERY("Prueba con otro nombre, dirección o número de estación."),
  LOAD_STATIONS("Cargar estaciones"),
  MAP_LEGEND_BIKES_AND_SLOTS("Bicis y huecos"),
  MAP_LEGEND_ONLY_BIKES_OR_SLOTS("Solo bicis o solo huecos"),
  MAP_LEGEND_OUT_OF_SERVICE("Sin servicio"),
  MAP_NO_STATIONS_WITHIN_RADIUS("No hay dentro de %s m"),
  MAP_NEAREST_STATION_LABEL("Estación más cercana"),
  MAP_SELECTED_STATION_LABEL("Estación seleccionada"),
  CLOSE("Cerrar"),
  MAP_NEAREST_FALLBACK_SUMMARY("La más cercana está a %s m · %s bicis · %s libres"),
  MAP_STATION_DISTANCE_SUMMARY("%s m · %s bicis · %s libres"),
  ROUTE("Ruta"),
  SAVED("Guardada"),
  SAVE("Guardar"),
  DETAILS("Detalle"),
  NEARBY_QUICK_ACTIONS_DESCRIPTION("Acciones rápidas para encontrar bicis, huecos y abrir rutas sin pasar por el mapa completo."),
  NEARBY_NEAR_YOU("Cerca de ti"),
  NEARBY_STATIONS_SORTED_DESCRIPTION("Estaciones ordenadas por cercanía y acciones rápidas para moverte."),
  NEARBY_NEAREST_WITH_BIKES("Más cercana con bicis"),
  NEARBY_NO_BIKES_NEARBY("Sin bicis cercanas"),
  NEARBY_NEAREST_WITH_SLOTS("Más cercana con huecos"),
  NEARBY_NO_SLOTS_NEARBY("Sin huecos cercanos"),
  NEARBY_UPDATING_STATIONS("Actualizando estaciones..."),
  NEARBY_STATIONS("Estaciones cercanas"),
  NEARBY_RADIUS_FALLBACK_HINT("Si no hay estaciones dentro del radio, te seguimos mostrando igualmente la más cercana."),
  NEARBY_CARD_ACTIONS_HINT("Toca cualquier tarjeta para abrir el detalle, guardarla o lanzar la ruta."),
  REFRESH_STATIONS("Actualizar estaciones"),
  FAVORITES_SUBTITLE("Tus estaciones guardadas para consultar el estado o abrir una ruta con un toque."),
  MY_STATIONS("Mis estaciones"),
  FAVORITES_SEARCH_STATION("Buscar estación para fijarla o filtrar favoritas"),
  HOME_AND_WORK("Casa y trabajo"),
  HOME_AND_WORK_DESCRIPTION("Puedes fijar Casa o Trabajo desde el buscador o directamente desde una favorita. Desliza una favorita para quitarla."),
  HOME("Casa"),
  WORK("Trabajo"),
  FAVORITES_EMPTY_TITLE("Todavía no tienes favoritas"),
  FAVORITES_EMPTY_DESCRIPTION("Guarda estaciones desde el mapa para consultarlas más rápido y compartirlas con el reloj."),
  PROFILE_SUBTITLE("Personaliza la experiencia de la app y comparte feedback cuando quieras."),
  NEARBY_STATION_RADIUS("Radio para estación cercana"),
  NEARBY_STATION_RADIUS_DESCRIPTION("Si no hay estaciones dentro del radio, la app mostrará igualmente la más cercana y te indicará la distancia."),
  RADIUS_ACTIVE("%s m activo"),
  SHORTCUTS("Atajos"),
  SHORTCUTS_REVIEW_COMMANDS("Consulta todos los comandos de voz disponibles y cómo invocarlos con %s."),
  OPEN_SHORTCUTS_GUIDE("Abrir guía de atajos"),
  APPEARANCE("Apariencia"),
  APPEARANCE_DESCRIPTION("Elige si la app sigue el sistema o usa siempre el tema claro u oscuro."),
  SYSTEM("Sistema"),
  LIGHT("Claro"),
  DARK("Oscuro"),
  IPHONE_ROUTE_APP("App de rutas en iPhone"),
  IPHONE_ROUTE_APP_DESCRIPTION("Elige qué app abrir para las rutas rápidas, el detalle de estación y los atajos de Siri."),
  IPHONE_ROUTE_APP_FALLBACK("Si Google Maps no está instalado, Bici Radar usará Apple Maps como fallback."),
  FEEDBACK_AND_SUGGESTIONS("Comentarios y sugerencias"),
  FEEDBACK_DESCRIPTION("¿Algo no funciona bien o tienes una idea? Usa el formulario para enviar tu opinión."),
  OPEN_FEEDBACK_FORM("Abrir formulario de feedback"),
  PRIVACY_AND_DATA("Privacidad y datos"),
  PRIVACY_DESCRIPTION("Consulta cómo gestiona Bici Radar la ubicación, los datos de uso y los accesos del dispositivo."),
  OPEN_PRIVACY_POLICY("Abrir política de privacidad"),
  BACK("Volver"),
  SHORTCUTS_IOS_SUBTITLE("Consulta qué puedes pedirle a Siri y cómo invocarlo de forma natural en Bici Radar."),
  HOW_TO_INVOKE("Cómo invocarlos"),
  SHORTCUTS_AVAILABLE_ON_IOS("Estas acciones quedan disponibles en Siri y Atajos."),
  SHORTCUTS_AVAILABLE_WITH_ASSISTANT("Qué puedes pedirle a %s y cómo invocarlo dentro de Bici Radar."),
  SHORTCUTS_IOS_INVOCATION_HINT("Abre Siri o Atajos y usa frases naturales como las de abajo terminando en “con Bici Radar”."),
  SHORTCUTS_ANDROID_INVOCATION_HINT("Abre Google Assistant y prueba frases naturales como las de abajo. Si hace falta, añade “con Bici Radar” para desambiguar."),
  SHORTCUTS_CURRENT_RADIUS("Radio actual para búsquedas cercanas: %s m."),
  LATEST_ANSWER("Última respuesta"),
  DISTANCE("Distancia"),
  SOURCE("Fuente"),
  SAVE_THIS_STATION("Guardar esta estación"),
  SAVE_THIS_STATION_DESCRIPTION("Márcala como favorita o fíjala como Casa o Trabajo para recuperarla más rápido desde Favoritas y con los atajos de voz."),
  FAVORITE("Favorita"),
  STATION_MARKED_HOME_AND_WORK("Ahora mismo esta estación está marcada como Casa y Trabajo."),
  STATION_MARKED_HOME("Ahora mismo esta estación está marcada como Casa."),
  STATION_MARKED_WORK("Ahora mismo esta estación está marcada como Trabajo."),
  TAP_HOME_OR_WORK_TO_ASSIGN("Puedes tocar Casa o Trabajo para asignarla directamente."),
  BIKES("Bicis"),
  SLOTS("Huecos"),
  OPEN_ROUTE("Abrir ruta"),
  REMOVE_FROM_FAVORITES("Quitar de favoritos"),
  TRIP_SUBTITLE("Busca la estación más cercana a tu destino y vigílala."),
  TRIP_STATION_FULL("Estación llena"),
  TRIP_STATION_NO_LONGER_HAS_SLOTS("\"%s\" ya no tiene plazas libres."),
  TRIP_SUGGESTED_ALTERNATIVE("Alternativa sugerida: %s%s — %s plazas."),
  TRIP_NO_NEARBY_ALTERNATIVE("No se encontró alternativa cercana con plazas."),
  GOT_IT("Entendido"),
  WHERE_ARE_YOU_GOING("¿Adónde vas?"),
  WALK_ROUTE_TO("Ruta a pie a %s"),
  TRIP_SUGGESTED_STATION("Estación sugerida"),
  FREE_SLOTS("Plazas libres"),
  STOP_MONITORING("Parar vigilancia"),
  REMOVE_FAVORITE("Quitar favorita"),
  GUIDE_NEAREST_STATION_DESCRIPTION("Encuentra la estación más cercana a tu ubicación actual y te abre la app en el contexto correcto."),
  GUIDE_NEAREST_STATION_EXAMPLE_NEAREST("Cuál es la estación más cercana con Bici Radar"),
  GUIDE_NEAREST_STATION_EXAMPLE_CLOSEST("Qué estación tengo más cerca con Bici Radar"),
  GUIDE_NEAREST_WITH_BIKES_OR_SLOTS("Más cercana con bicis o huecos"),
  GUIDE_NEAREST_WITH_BIKES_OR_SLOTS_DESCRIPTION("Busca la mejor estación cercana para coger bici o para devolverla con huecos libres."),
  GUIDE_NEAREST_WITH_BIKES_OR_SLOTS_EXAMPLE_BIKES("Dónde hay bicis cerca con Bici Radar"),
  GUIDE_NEAREST_WITH_BIKES_OR_SLOTS_EXAMPLE_SLOTS("Dónde puedo dejar la bici con Bici Radar"),
  GUIDE_STATION_STATUS("Estado de una estación"),
  GUIDE_STATION_STATUS_DESCRIPTION("Consulta una estación concreta por nombre, dirección, número o usando tus alias de Casa y Trabajo."),
  GUIDE_STATION_STATUS_EXAMPLE_HOME("Cómo está casa con Bici Radar"),
  GUIDE_STATION_STATUS_EXAMPLE_HOME_BIKES("Cuántas bicis hay en casa con Bici Radar"),
  GUIDE_STATION_STATUS_EXAMPLE_STATION_SLOTS("Cuántos huecos hay en la estación 48 con Bici Radar"),
  GUIDE_FAVORITES_DESCRIPTION("Abre directamente tu lista de favoritas, con Casa y Trabajo incluidos cuando estén configurados."),
  GUIDE_FAVORITES_EXAMPLE_OPEN("Abre mis favoritas con Bici Radar"),
  GUIDE_FAVORITES_EXAMPLE_WORK("Cómo está trabajo con Bici Radar"),
  GUIDE_ROUTE_TO_STATION("Ruta a una estación"),
  GUIDE_ROUTE_TO_STATION_DESCRIPTION("Lanza la ruta rápida hacia una estación concreta o hacia Casa y Trabajo si ya los has configurado."),
  GUIDE_ROUTE_TO_STATION_EXAMPLE_PLAZA_ESPANA("Llévame a Plaza España con Bici Radar"),
  GUIDE_ROUTE_TO_STATION_EXAMPLE_WORK("Llévame al trabajo con Bici Radar"),
  TRIP_NO_STATION_WITH_FREE_SLOTS_NEARBY("No se encontró ninguna estación con plazas libres cerca."),
  METERS("%s m"),
  SAVE_TO_FAVORITES("Guardar en favoritos"),
  DELETE_FAVORITE("Eliminar favorita"),
  MAP_UNAVAILABLE_GOOGLE_API_KEY("Mapa no disponible. Configura una API key de Google Maps."),
  MAP_STATION_BIKES_FREE("%s bicis · %s libres"),
  MAP_STATION_BIKES_SLOTS_DISTANCE("%s bicis · %s huecos · %s m"),
  DESTINATION("Destino"),
  ASK_ABOUT_STATIONS_FAVORITES_OR_ROUTES("Pregunta por estaciones cercanas, favoritas o rutas."),
  TRIP_SEARCH_LOCATION_UNAVAILABLE("No hemos podido buscar esa ubicación ahora mismo."),
  TRIP_LOCATION_SERVICE_UNAVAILABLE("No hemos podido conectar con el servicio de localización."),
  SEARCH_ERROR("Error de búsqueda: %s"),
  UNKNOWN("desconocido"),
  TRIP_NO_STATION_DATA_AVAILABLE("No hay datos de estaciones disponibles."),
  CHANGELOG_WHATS_NEW("Novedades"),
  CHANGELOG_DARK_THEME_TITLE("Tema oscuro"),
  CHANGELOG_DARK_THEME_DESCRIPTION("La app se adapta automáticamente al modo oscuro del sistema."),
  CHANGELOG_DISMISSIBLE_CARD_TITLE("Tarjeta descartable"),
  CHANGELOG_DISMISSIBLE_CARD_DESCRIPTION("Ahora puedes cerrar la tarjeta de estación en el mapa con el botón X."),
  CHANGELOG_MAP_FILTERS_TITLE("Filtros en el mapa"),
  CHANGELOG_MAP_FILTERS_DESCRIPTION("Filtra estaciones por disponibilidad: bicis + huecos, solo bicis o solo huecos."),
  CHANGELOG_REFRESH_INDICATOR_TITLE("Indicador de refresco"),
  CHANGELOG_REFRESH_INDICATOR_DESCRIPTION("Cuenta atrás visible junto al botón de refresco (actualización cada 5 min)."),
  DESTINATION_PLACEHOLDER("Escribe una dirección o lugar"),
  CLEAR_FIELD("Borrar"),
  CANCEL_MAP("Cancelar mapa"),
  PICK_ON_MAP("Elegir en mapa"),
  TAP_MAP_TO_PICK_DESTINATION("Toca el mapa para elegir destino"),
  SUGGESTIONS("Sugerencias"),
  SEARCHING_NEARBY_STATION("Buscando estación cercana..."),
  MONITOR_THIS_STATION("Vigilar esta estación"),
  MONITOR_THIS_STATION_DESCRIPTION("Recibirás una notificación si se llena antes de que llegues."),
  START_MONITORING("Iniciar vigilancia"),
  MONITORING_ACTIVE("Vigilancia activa"),
  REMAINING_TIME("Tiempo restante: %s"),
  MONITORING_ACTIVE_DESCRIPTION("Se comprueba cada 30 s. Notificación si la estación se llena."),
  SAVED_PLACE_NOT_SET("Todavía no has fijado una estación para %s."),
  ASSIGN_SEARCH_RESULT("Asignar búsqueda"),
  REMOVE("Quitar"),
  CURRENT_SEARCH_ASSIGNMENT_HINT("La búsqueda actual apunta a %s. Se usará para %s si pulsas asignar."),
  USE_SEARCH_TO_ASSIGN_STATION("Usa el buscador de arriba para elegir una estación y asignarla."),
  CLEAR_SEARCH("Limpiar búsqueda"),
  REFRESH_STATIONS_TO_OPEN_ROUTE("Actualiza estaciones para poder abrir la ruta."),
  QUICK_ROUTE_FALLBACK_SUMMARY("No hay dentro de %s m. La más cercana está a %s m."),
  QUICK_ROUTE_DISTANCE_SUMMARY("%s m · %s bicis · %s huecos"),
  MY_FAVORITES("Mis favoritas"),
  ASSISTANT_LABEL_NEAREST_WITH_BIKES("Cercana con bicis"),
  ASSISTANT_LABEL_NEAREST_WITH_SLOTS("Cercana con huecos"),
  BIKES_IN_STATION("Bicis en estación"),
  SLOTS_IN_STATION("Huecos en estación"),
  ROUTE_TO_STATION("Ruta a estación"),
  STATION_STATUS_LABEL("Estado de estación"),
  CLEAR("Limpiar"),
}

fun sharedString(key: SharedString): String = localizedText(key.fallback)

fun sharedString(key: SharedString, vararg args: Any?): String = localizedText(key.fallback, *args)
