/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-container': 'var(--secondary-container)',
        'on-surface': 'var(--on-surface)',
        'inverse-on-surface': 'var(--inverse-on-surface)',
        'outline': 'var(--outline)',
        'surface-container-high': 'var(--surface-container-high)',
        'on-primary-fixed-variant': 'var(--on-primary-fixed-variant)',
        'error': 'var(--error)',
        'background': 'var(--background)',
        'tertiary': 'var(--tertiary)',
        'primary-fixed-dim': 'var(--primary-fixed-dim)',
        'surface-container-low': 'var(--surface-container-low)',
        'tertiary-dim': 'var(--tertiary-dim)',
        'surface-tint': 'var(--surface-tint)',
        'on-secondary-fixed': 'var(--on-secondary-fixed)',
        'on-secondary-container': 'var(--on-secondary-container)',
        'secondary': 'var(--secondary)',
        'error-dim': 'var(--error-dim)',
        'on-error-container': 'var(--on-error-container)',
        'primary-dim': 'var(--primary-dim)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'surface-bright': 'var(--surface-bright)',
        'error-container': 'var(--error-container)',
        'on-tertiary-container': 'var(--on-tertiary-container)',
        'on-tertiary': 'var(--on-tertiary)',
        'on-primary': 'var(--on-primary)',
        'on-error': 'var(--on-error)',
        'primary-container': 'var(--primary-container)',
        'on-tertiary-fixed': 'var(--on-tertiary-fixed)',
        'secondary-fixed-dim': 'var(--secondary-fixed-dim)',
        'on-secondary': 'var(--on-secondary)',
        'inverse-surface': 'var(--inverse-surface)',
        'on-background': 'var(--on-background)',
        'primary-fixed': 'var(--primary-fixed)',
        'tertiary-fixed-dim': 'var(--tertiary-fixed-dim)',
        'primary': 'var(--primary)',
        'surface': 'var(--surface)',
        'tertiary-fixed': 'var(--tertiary-fixed)',
        'tertiary-container': 'var(--tertiary-container)',
        'secondary-dim': 'var(--secondary-dim)',
        'outline-variant': 'var(--outline-variant)',
        'surface-variant': 'var(--surface-variant)',
        'secondary-fixed': 'var(--secondary-fixed)',
        'inverse-primary': 'var(--inverse-primary)',
        'surface-dim': 'var(--surface-dim)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'on-primary-container': 'var(--on-primary-container)',
        'on-primary-fixed': 'var(--on-primary-fixed)',
        'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant)',
        'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'surface-container': 'var(--surface-container)',
      },
      fontFamily: {
        'headline': ['Space Grotesk'],
        'body': ['Manrope'],
        'label': ['Manrope'],
      },
    },
  },
  plugins: [],
}